package codigo;

import java_cup.runtime.Symbol;

parser code
{:
    private Symbol s;
    
    public void syntax_error(Symbol s){
        this.s = s;
    }

    public Symbol getS(){
        return this.s;
}
:};

terminal Linea, Int, Bool, If, Else, Do, While, StopLoop,
    SpinCraneLeft, SpinCraneRight, MoveFowardCrane, MoveBackCrane,
    SpinBallLeft, SpinBallRight, HitToTheLeft, HitToTheRight,
    Igual, Suma, Resta, Multiplicacion, Division, Op_logico, Op_relacional,
    Op_atribucion, Op_incremento, Op_booleano, Parentesis_a, Parentesis_c,
    Llave_a, Llave_c, Corchete_a, Corchete_c, Start, P_coma, Identificador,
    Numero, WaitTime, ERROR;
non terminal INICIO, SENTENCIA, DECLARACION, DECLARACION_FOR, IF, ELSE,
    WHILE, DO_WHILE, SENTENCIA_BOOLEANA, SENTENCIA_ARITMETICA;

start with INICIO;

INICIO ::= 
    Start Parentesis_a Parentesis_c Llave_a SENTENCIA Llave_c {:
    PrincipalCompi.status--;
    PrincipalCompi.ci=PrincipalCompi.sentencia[PrincipalCompi.status];
    PrincipalCompi.gramatica="INICIO ::= Start Parentesis_a Parentesis_c Llave_a SENTENCIA Llave_c\n\n"+PrincipalCompi.gramatica;
    :}|
    Start Parentesis_a Parentesis_c Llave_a SENTENCIA:i {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(iright+1)+"; falta una llave de cierre");
    PrincipalCompi.gramatica="INICIO ::= Start Parentesis_a Parentesis_c Llave_a SENTENCIA >>Llave_c<<\n\n"+PrincipalCompi.gramatica;
    :} |
    Start Parentesis_a Parentesis_c:i SENTENCIA Llave_c {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(iright+1)+"; falta una llave de apertura");
    PrincipalCompi.gramatica="INICIO ::= Start Parentesis_a Parentesis_c >>Llave_a<< SENTENCIA Llave_c\n\n"+PrincipalCompi.gramatica;
    :} |
    Start Parentesis_a:i Llave_a SENTENCIA Llave_c {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(iright+1)+"; falta un paréntesis de cierre");
    PrincipalCompi.gramatica="INICIO ::= Start Parentesis_a >>Parentesis_c<< Llave_a SENTENCIA Llave_c\n\n"+PrincipalCompi.gramatica;
    :} |
    Start:i Parentesis_c Llave_a SENTENCIA Llave_c {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(iright+1)+"; falta un paréntesis de apertura");
    PrincipalCompi.gramatica="INICIO ::= Start >>Parentesis_a<< Parentesis_c Llave_a SENTENCIA Llave_c\n\n"+PrincipalCompi.gramatica;
    :} |
    Identificador:i Parentesis_a Parentesis_c Llave_a SENTENCIA Llave_c {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(iright+1)+"; comienzo de programa incorrecto");
    PrincipalCompi.gramatica="INICIO ::= >>Start<< Parentesis_a Parentesis_c Llave_a SENTENCIA Llave_c\n\n"+PrincipalCompi.gramatica;
    :}|
    Identificador:i Parentesis_a Parentesis_c Llave_a SENTENCIA {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(iright+1)+"; comienzo de programa incorrecto");
    PrincipalCompi.gramatica="INICIO ::= >>Start<< Parentesis_a Parentesis_c Llave_a SENTENCIA Llave_c\n\n"+PrincipalCompi.gramatica;
    :} |
    Identificador:i Parentesis_a Parentesis_c SENTENCIA Llave_c {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(iright+1)+"; comienzo de programa incorrecto");
    PrincipalCompi.gramatica="INICIO ::= >>Start<< Parentesis_a Parentesis_c Llave_a SENTENCIA Llave_c\n\n"+PrincipalCompi.gramatica;
    :} |
    Identificador:i Parentesis_a Llave_a SENTENCIA Llave_c {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(iright+1)+"; comienzo de programa incorrecto");
    PrincipalCompi.gramatica="INICIO ::= >>Start<< Parentesis_a Parentesis_c Llave_a SENTENCIA Llave_c\n\n"+PrincipalCompi.gramatica;
    :} |
    Identificador:i Parentesis_c Llave_a SENTENCIA Llave_c {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(iright+1)+"; comienzo de programa incorrecto");
    PrincipalCompi.gramatica="INICIO ::= >>Start<< Parentesis_a Parentesis_c Llave_a SENTENCIA Llave_c\n\n"+PrincipalCompi.gramatica;
    :} |


    Start Parentesis_a Parentesis_c Llave_a Llave_c {:
    PrincipalCompi.gramatica="INICIO ::= Start Parentesis_a Parentesis_c Llave_a Llave_c\n\n"+PrincipalCompi.gramatica;
    :} |
    Start Parentesis_a Parentesis_c Llave_a:i {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(iright+1)+"; falta una llave de cierre");
    PrincipalCompi.gramatica="INICIO ::= Start Parentesis_a Parentesis_c Llave_a >>Llave_c<<\n\n"+PrincipalCompi.gramatica;
    :} |
    Start Parentesis_a Parentesis_c:i Llave_c {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(iright+1)+"; falta una llave de apertura");
    PrincipalCompi.gramatica="INICIO ::= Start Parentesis_a Parentesis_c >>Llave_a<< Llave_c\n\n"+PrincipalCompi.gramatica;
    :} |
    Start Parentesis_a:i Llave_a Llave_c {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(iright+1)+"; falta un paréntesis de cierre");
    PrincipalCompi.gramatica="INICIO ::= Start Parentesis_a >>Parentesis_c<< Llave_a Llave_c\n\n"+PrincipalCompi.gramatica;
    :} |
    Start:i Parentesis_c Llave_a Llave_c {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(iright+1)+"; falta un paréntesis de apertura");
    PrincipalCompi.gramatica="INICIO ::= Start >>Parentesis_a<< Parentesis_c Llave_a Llave_c\n\n"+PrincipalCompi.gramatica;
    :} |
    Identificador:i Parentesis_a Parentesis_c Llave_a Llave_c {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(iright+1)+"; comienzo de programa incorrecto");
    PrincipalCompi.gramatica="INICIO ::= >>Start<< Parentesis_a Parentesis_c Llave_a Llave_c\n\n"+PrincipalCompi.gramatica;
    :}|
    Identificador:i Parentesis_a Parentesis_c Llave_a {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(iright+1)+"; comienzo de programa incorrecto");
    PrincipalCompi.gramatica="INICIO ::= >>Start<< Parentesis_a Parentesis_c Llave_a Llave_c\n\n"+PrincipalCompi.gramatica;
    :} |
    Identificador:i Parentesis_a Parentesis_c Llave_c {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(iright+1)+"; comienzo de programa incorrecto");
    PrincipalCompi.gramatica="INICIO ::= >>Start<< Parentesis_a Parentesis_c Llave_a Llave_c\n\n"+PrincipalCompi.gramatica;
    :} |
    Identificador:i Parentesis_a Llave_a Llave_c {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(iright+1)+"; comienzo de programa incorrecto");
    PrincipalCompi.gramatica="INICIO ::= >>Start<< Parentesis_a Parentesis_c Llave_a Llave_c\n\n"+PrincipalCompi.gramatica;
    :} |
    Identificador:i Parentesis_c Llave_a Llave_c {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(iright+1)+"; comienzo de programa incorrecto");
    PrincipalCompi.gramatica="INICIO ::= >>Start<< Parentesis_a Parentesis_c Llave_a Llave_c\n\n"+PrincipalCompi.gramatica;
    :} |
;
SENTENCIA ::= 
    SENTENCIA DECLARACION {:
    PrincipalCompi.status--;
    PrincipalCompi.sentencia[PrincipalCompi.status]=PrincipalCompi.sentencia[PrincipalCompi.status]+PrincipalCompi.declaracion;
    PrincipalCompi.declaracion="";
    PrincipalCompi.status++;
    PrincipalCompi.gramatica="SENTENCIA ::= SENTENCIA DECLARACION\n\n"+PrincipalCompi.gramatica;
    :}|
    DECLARACION {:
    PrincipalCompi.sentencia[PrincipalCompi.status]=PrincipalCompi.declaracion;
    PrincipalCompi.declaracion="";
    PrincipalCompi.status++;
    PrincipalCompi.gramatica="SENTENCIA ::= DECLARACION\n\n"+PrincipalCompi.gramatica;
    :}|
    SENTENCIA IF {:
    PrincipalCompi.status--;
    PrincipalCompi.sentencia[PrincipalCompi.status]=PrincipalCompi.sentencia[PrincipalCompi.status]+PrincipalCompi.ifs;
    PrincipalCompi.ifs="";
    PrincipalCompi.status++;
    PrincipalCompi.gramatica="SENTENCIA ::= SENTENCIA IF\n\n"+PrincipalCompi.gramatica;
    :}| 
    IF {:
    PrincipalCompi.sentencia[PrincipalCompi.status]=PrincipalCompi.ifs;
    PrincipalCompi.ifs="";
    PrincipalCompi.status++;
    PrincipalCompi.gramatica="SENTENCIA ::= IF\n\n"+PrincipalCompi.gramatica;
    :}|
    SENTENCIA WHILE {:
    PrincipalCompi.status--;
    PrincipalCompi.sentencia[PrincipalCompi.status]=PrincipalCompi.sentencia[PrincipalCompi.status]+PrincipalCompi.whiles;
    PrincipalCompi.whiles="";
    PrincipalCompi.status++;
    PrincipalCompi.gramatica="SENTENCIA ::= SENTENCIA WHILE\n\n"+PrincipalCompi.gramatica;
    :} |
    WHILE {:
    PrincipalCompi.sentencia[PrincipalCompi.status]=PrincipalCompi.whiles;
    PrincipalCompi.whiles="";
    PrincipalCompi.status++;
    PrincipalCompi.gramatica="SENTENCIA ::= WHILE\n\n"+PrincipalCompi.gramatica;
    :} |
    SENTENCIA DO_WHILE {:
    PrincipalCompi.status--;
    PrincipalCompi.sentencia[PrincipalCompi.status]=PrincipalCompi.sentencia[PrincipalCompi.status]+PrincipalCompi.dowhiles;
    PrincipalCompi.dowhiles="";
    PrincipalCompi.status++;
    PrincipalCompi.gramatica="SENTENCIA ::= SENTENCIA DO_WHILE\n\n"+PrincipalCompi.gramatica;
    :} |
    DO_WHILE {:
    PrincipalCompi.sentencia[PrincipalCompi.status]=PrincipalCompi.dowhiles;
    PrincipalCompi.dowhiles="";
    PrincipalCompi.status++;
    PrincipalCompi.gramatica="SENTENCIA ::= DO_WHILE\n\n"+PrincipalCompi.gramatica;
    :} 
;
DECLARACION ::= 
    Int:t Identificador:i P_coma {:
    PrincipalCompi.declaracion="("+t+", , ,"+i+")\n";
    int n=0;
    Simbolo temp=null;
    Simbolo s=new Simbolo(i,t,null);
    if(PrincipalCompi.tabla_simbolos.isEmpty()){
        PrincipalCompi.tabla_simbolos.add(s);
        PrincipalCompi.gramatica="DECLARACION ::= Int:t Identificador:i P_coma\n\n"+PrincipalCompi.gramatica;
    }else{
        for(int it=0;it<PrincipalCompi.tabla_simbolos.size();it++){
            temp=PrincipalCompi.tabla_simbolos.get(it);
            if(temp.getNombre().equals(i)){
                PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" ya fue declarado anteriormente");
                PrincipalCompi.gramatica="DECLARACION ::= Int:t >>Identificador:i<< P_coma\n\n"+PrincipalCompi.gramatica;
                n++;
                break;
            }
        }
        if(n==0){
            PrincipalCompi.tabla_simbolos.add(s);
            PrincipalCompi.gramatica="DECLARACION ::= Int:t Identificador:i P_coma\n\n"+PrincipalCompi.gramatica;
        }
    }
    :} |
    Int:t Identificador:i {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(iright+1)+"; falta un punto y coma al final de la sentencia");
    PrincipalCompi.gramatica="DECLARACION ::= Int:t Identificador:i >>P_coma<<\n\n"+PrincipalCompi.gramatica;
    :} |
    Int:t P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(tright+1)+"; falta la declaración de un identificador");
    PrincipalCompi.gramatica="DECLARACION ::= Int:t >>Identificador:i<< P_coma\n\n"+PrincipalCompi.gramatica;
    :} |
    Identificador:i P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(iright+1)+"; falta la asignación de un tipo de dato");
    PrincipalCompi.gramatica="DECLARACION ::= >>Int:t<< Identificador:i P_coma\n\n"+PrincipalCompi.gramatica;
    :} |


    Bool:t Identificador:i P_coma {:
    PrincipalCompi.declaracion="("+t+", , ,"+i+")\n";
    int n=0;
    Simbolo temp=null;
    Simbolo s=new Simbolo(i,t,null);
    if(PrincipalCompi.tabla_simbolos.isEmpty()){
        PrincipalCompi.tabla_simbolos.add(s);
        PrincipalCompi.gramatica="DECLARACION ::= Bool:t Identificador:i P_coma\n\n"+PrincipalCompi.gramatica;
    }else{
        for(int it=0;it<PrincipalCompi.tabla_simbolos.size();it++){
            temp=PrincipalCompi.tabla_simbolos.get(it);
            if(temp.getNombre().equals(i)){
                PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" ya fue declarado anteriormente");
                PrincipalCompi.gramatica="DECLARACION ::= Bool:t >>Identificador:i<< P_coma\n\n"+PrincipalCompi.gramatica;
                n++;
                break;
            }
        }
        if(n==0){
            PrincipalCompi.tabla_simbolos.add(s);
            PrincipalCompi.gramatica="DECLARACION ::= Bool:t Identificador:i P_coma\n\n"+PrincipalCompi.gramatica;
        }
    }
    :} |
    Bool:t Identificador:i {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(iright+1)+"; falta un punto y coma al final de la sentencia");
    :} |
    Bool:t P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(tright+1)+"; falta la declaración de un identificador");
    :} |


    Int:t Identificador:i Igual:g Identificador:l P_coma {:
    PrincipalCompi.declaracion="("+t+", , ,"+i+")\n("+g+","+l+", ,"+i+")\n";
    int n=0;
    Simbolo temp=null;
    if(PrincipalCompi.tabla_simbolos.isEmpty()){
        PrincipalCompi.err.add("Error semántico linea:"+(lright+1)+"; el identificador "+l+" no ha sido declarado");
    }else{
        for(int it=0;it<PrincipalCompi.tabla_simbolos.size();it++){
            temp=PrincipalCompi.tabla_simbolos.get(it);
            if(temp.getNombre().equals(i)){
                n++;
                PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" ya fue declarado anteriormente");
                break;
            }else if(temp.getNombre().equals(l)){
                if(temp.getTipo().equals(t)){
                    if(temp.getValor()==null){
                        n++;
                        PrincipalCompi.err.add("Error semántico linea:"+(lright+1)+"; el identificador "+l+" no ha sido inicializado");
                        break;
                    }else{
                        n++;
                        Object v=temp.getValor();
                        Simbolo s=new Simbolo(i,t,v);
                        PrincipalCompi.tabla_simbolos.add(s);
                        PrincipalCompi.gramatica="DECLARACION ::= Int:t Identificador:i Igual:g Identificador:l P_coma\n\n"+PrincipalCompi.gramatica;
                        break;
                    }
                }else{
                    n++;
                    PrincipalCompi.err.add("Error semántico linea:"+(lright+1)+"; el valor de "+l+" no es de tipo int");
                    break;
                }
            }
        }
        if(n==0){
            PrincipalCompi.err.add("Error semántico linea:"+(lright+1)+"; el identificador "+l+" no ha sido declarado");
        }
    }
    :} |
    Int:t Identificador:i Igual:g Identificador:l {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(iright+1)+"; falta un punto y coma al final de la sentencia");
    :} |
    Int:t Identificador:i Igual:g P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(iright+1)+"; falta un valor entero o identificador tipo int para asignar");
    :} |
    /*Int:t Identificador:i Identificador:l P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(iright+1)+"; falta un signo de igual");
    :} |*/
    Int:t Igual:g Identificador:l P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(tright+1)+"; falta la declaración de un identificador");
    :} |


    Bool:t Identificador:i Igual:g Identificador:l P_coma {:
    PrincipalCompi.declaracion="("+t+", , ,"+i+")\n("+g+","+l+", ,"+i+")\n";
    int n=0;
    Simbolo temp=null;
    if(PrincipalCompi.tabla_simbolos.isEmpty()){
        PrincipalCompi.err.add("Error semántico linea:"+(lright+1)+"; el identificador "+l+" no ha sido declarado");
    }else{
        for(int it=0;it<PrincipalCompi.tabla_simbolos.size();it++){
            temp=PrincipalCompi.tabla_simbolos.get(it);
            if(temp.getNombre().equals(i)){
                n++;
                PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" ya fue declarado anteriormente");
                break;
            }else if(temp.getNombre().equals(l)){
                if(temp.getTipo().equals(t)){
                    if(temp.getValor()==null){
                        n++;
                        PrincipalCompi.err.add("Error semántico linea:"+(lright+1)+"; el identificador "+l+" no ha sido inicializado");
                        break;
                    }else{
                        n++;
                        Object v=temp.getValor();
                        Simbolo s=new Simbolo(i,t,v);
                        PrincipalCompi.tabla_simbolos.add(s);
                        PrincipalCompi.gramatica="DECLARACION ::= Bool:t Identificador:i Igual:g Identificador:l P_coma\n\n"+PrincipalCompi.gramatica;
                        break;
                    }
                }else{
                    n++;
                    PrincipalCompi.err.add("Error semántico linea:"+(lright+1)+"; el valor de "+l+" no es de tipo bool");
                    break;
                }
            }
        }
        if(n==0){
            PrincipalCompi.err.add("Error semántico linea:"+(lright+1)+"; el identificador "+l+" no ha sido declarado");
        }
    }
    :} |
    Bool:t Identificador:i Igual:g Identificador:l {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(iright+1)+"; falta un punto y coma al final de la sentencia");
    :} |
    /*Bool:t Identificador:i Igual:g P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(iright+1)+"; falta un valor booleano o identificador tipo bool para asignar");
    :} |*/
    /*Bool:t Identificador:i Identificador:l P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(iright+1)+"; falta un signo de igual");
    :} |*/
    Bool:t Igual:g Identificador:l P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(tright+1)+"; falta la declaración de un identificador");
    :} |


    Identificador:a Igual:g Identificador:b P_coma {:
    PrincipalCompi.declaracion="("+g+","+b+", ,"+a+")";
    int n=0;
    Simbolo s1=null;
    Simbolo s2=null;
    if(PrincipalCompi.tabla_simbolos.isEmpty()){
        PrincipalCompi.err.add("Error semántico linea:"+(aright+1)+"; el identificador "+a+" y "+b+" no han sido declarados");
    }else{
        for(int it=0;it<PrincipalCompi.tabla_simbolos.size();it++){
            Simbolo temp=PrincipalCompi.tabla_simbolos.get(it);
            if(temp.getNombre().equals(a)){
                s1=temp;
                for(int at=0;at<PrincipalCompi.tabla_simbolos.size();at++){
                    Simbolo temp2=PrincipalCompi.tabla_simbolos.get(at);
                    if(temp2.getNombre().equals(b)){
                        s2=temp2;
                        if(temp.getTipo().equals(temp2.getTipo())){
                            if(temp2.getValor()==null){
                                n++;
                                PrincipalCompi.err.add("Error semántico linea:"+(bright+1)+"; el identificador "+b+" no ha sido inicializado");
                                break;
                            }else{
                                n++;
                                Object v=temp2.getValor();
                                temp.setValor(v);
                                PrincipalCompi.gramatica="DECLARACION ::= Identificador:a Igual:g Identificador:b P_coma\n\n"+PrincipalCompi.gramatica;
                                break;
                            }
                        }else{
                            n++;
                            PrincipalCompi.err.add("Error semántico linea:"+(aright+1)+"; los tipos de dato de "+a+" y "+b+" son incompatibles");
                            break;
                        }
                    }
                }
            }
        }
        if(n==0){
            if(s1==null){
                PrincipalCompi.err.add("Error semántico linea:"+(aright+1)+"; el identificador "+a+" no ha sido declarado");
            }
            if(s2==null){
                PrincipalCompi.err.add("Error semántico linea:"+(bright+1)+"; el identificador "+b+" no ha sido declarado");
            }
        }
    }
    :} |
    Identificador:a Igual:g Identificador:b {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un punto y coma al final de la sentencia");
    :} |
    /*Identificador:a Igual:g P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un valor o identificador para asignar");
    :} |*/
    Identificador:a Identificador:b P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un signo de igual");
    :} |
    /*Igual:g Identificador:b P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(iright+1)+"; falta un identificador declarado");
    :} |*/


    Int:t Identificador:i Igual:g SENTENCIA_ARITMETICA P_coma {:
    PrincipalCompi.declaracion="("+t+", , ,"+i+")\n"+PrincipalCompi.s_arit+"("+g+",TA"+PrincipalCompi.temp+", ,"+i+")\n";
    PrincipalCompi.temp++;
    PrincipalCompi.s_arit="";
    Simbolo a=null;
        for(int it=0;it<PrincipalCompi.tabla_simbolos.size();it++){
            if(i.equals(PrincipalCompi.tabla_simbolos.get(it).getNombre().toString())){
                a=PrincipalCompi.tabla_simbolos.get(it);
            }
        }
        if(a==null){
            a=new Simbolo(i,t,PrincipalCompi.value);
            PrincipalCompi.tabla_simbolos.add(a);
            PrincipalCompi.value=null;
            PrincipalCompi.gramatica="DECLARACION ::= Int:t Identificador:i Igual:g SENTENCIA_ARITMETICA P_coma\n\n"+PrincipalCompi.gramatica;
        }else{
            PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" ya fue declarado anteriormente");
        }
    :} |
    Int:t Identificador:i Igual:g SENTENCIA_ARITMETICA {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(iright+1)+"; falta un punto y coma al final de la sentencia");
    :} |
    /*Int:t Identificador:i SENTENCIA_ARITMETICA P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un signo de igual");
    :} |*/
    Int:t Igual:g SENTENCIA_ARITMETICA P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(tright+1)+"; falta la declaración de un identificador");
    :} |

    Identificador:i Igual:g SENTENCIA_ARITMETICA P_coma {:
    PrincipalCompi.declaracion=PrincipalCompi.s_arit+"("+g+",TA"+PrincipalCompi.temp+", ,"+i+")\n";
    PrincipalCompi.temp++;
    PrincipalCompi.s_arit="";
    Simbolo a=null;
        for(int it=0;it<PrincipalCompi.tabla_simbolos.size();it++){
            if(i.equals(PrincipalCompi.tabla_simbolos.get(it).getNombre().toString())){
                a=PrincipalCompi.tabla_simbolos.get(it);
            }
        }
        if(a==null){
            PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido declarado");
        }else{
            if(a.getTipo().toString().equals("int")){
                a.setValor(PrincipalCompi.value);
                PrincipalCompi.gramatica="DECLARACION ::= Identificador:i Igual:g SENTENCIA_ARITMETICA P_coma\n\n"+PrincipalCompi.gramatica;
                PrincipalCompi.value=null;
            }else{
                PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no es de tipo int");
            }
        }
    :} |
    Identificador:i Igual:g SENTENCIA_ARITMETICA {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(iright+1)+"; falta un punto y coma al final de la sentencia");
    :} |
    Identificador:i SENTENCIA_ARITMETICA P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(iright+1)+"; falta un signo de igual");
    :} |
    /*Igual:g SENTENCIA_ARITMETICA P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(iright+1)+"; falta un identificador declarado");
    :} |*/


    Bool:t Identificador:i Igual:g SENTENCIA_BOOLEANA P_coma {:
    PrincipalCompi.declaracion="("+t+", , ,"+i+")\n"+PrincipalCompi.s_bool+"("+g+",TB"+PrincipalCompi.temp+", ,"+i+")\n";
    PrincipalCompi.temp++;
    PrincipalCompi.s_bool="";
    Simbolo a=null;
        for(int it=0;it<PrincipalCompi.tabla_simbolos.size();it++){
            if(i.equals(PrincipalCompi.tabla_simbolos.get(it).getNombre().toString())){
                a=PrincipalCompi.tabla_simbolos.get(it);
            }
        }
        if(a==null){
            a=new Simbolo(i,t,PrincipalCompi.valueb);
            PrincipalCompi.tabla_simbolos.add(a);
            PrincipalCompi.gramatica="DECLARACION ::= Bool:t Identificador:i Igual:g SENTENCIA_BOOLEANA P_coma\n\n"+PrincipalCompi.gramatica;
            PrincipalCompi.valueb=null;
        }else{
            PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" ya fue declarado anteriormente");
        }
    :} |
    /*Bool:t Identificador:i Igual:g SENTENCIA_BOOLEANA {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(iright+1)+"; falta un punto y coma al final de la sentencia");
    :} |*/
    /*Bool:t Identificador:i SENTENCIA_BOOLEANA P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(iright+1)+"; falta un signo de igual");
    :} |*/
    Bool:t Igual:g SENTENCIA_BOOLEANA P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(tright+1)+"; falta la declaración de un identificador");
    :} |


    Identificador:i Igual:g SENTENCIA_BOOLEANA P_coma {:
    PrincipalCompi.declaracion=PrincipalCompi.s_bool+"("+g+",TB"+PrincipalCompi.temp+", ,"+i+")\n";
    PrincipalCompi.temp++;
    PrincipalCompi.s_bool="";
    Simbolo a=null;
        for(int it=0;it<PrincipalCompi.tabla_simbolos.size();it++){
            if(i.equals(PrincipalCompi.tabla_simbolos.get(it).getNombre().toString())){
                a=PrincipalCompi.tabla_simbolos.get(it);
            }
        }
        if(a==null){
            PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido declarado");
        }else{
            if(a.getTipo().toString().equals("bool")){
                a.setValor(PrincipalCompi.valueb);
                PrincipalCompi.gramatica="DECLARACION ::= Identificador:i Igual:g SENTENCIA_BOOLEANA P_coma\n\n"+PrincipalCompi.gramatica;
                PrincipalCompi.valueb=null;
            }else{
                PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no es de tipo bool");
            }
        }
    :} |
    /*Identificador:i Igual:g SENTENCIA_BOOLEANA {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(iright+1)+"; falta un punto y coma al final de la sentencia");
    :} |*/
    /*Identificador:i SENTENCIA_BOOLEANA P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(iright+1)+"; falta un signo de igual");
    :} |*/
    /*Igual:g SENTENCIA_BOOLEANA P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(iright+1)+"; falta un identificador declarado");
    :} |*/


    Identificador:i Op_incremento:o P_coma {:
    PrincipalCompi.declaracion="("+o+", , ,"+i+")\n";
    int n=0;
    Simbolo temp=null;
    if(PrincipalCompi.tabla_simbolos.isEmpty()){
        PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido declarado");
    }else{
        for(int it=0;it<PrincipalCompi.tabla_simbolos.size();it++){
            temp=PrincipalCompi.tabla_simbolos.get(it);
            if(temp.getNombre().equals(i)){
                if(temp.getTipo().toString().equals("int")){
                    if(temp.getValor()==null){
                        PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido inicializado");
                        n++;
                        break;
                    }else{
                        int num=Integer.parseInt(temp.getValor().toString());
                        num++;
                        temp.setValor(num);
                        n++;
                        PrincipalCompi.gramatica="DECLARACION ::= Identificador:i Op_incremento:o P_coma\n\n"+PrincipalCompi.gramatica;
                        break;
                    }
                }else{
                    PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no es de tipo int");
                    n++;
                    break;
                }
            }
        }
        if(n==0){
            PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido declarado");
        }
    }
    :} |
    Identificador:i Op_incremento:o {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(iright+1)+"; falta un punto y coma al final de la sentencia");
    :} |
    Op_incremento:o P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(oright+1)+"; falta un identificador declarado");
    :} |


    Int:t Identificador:i Igual:g Numero:n P_coma{:
    PrincipalCompi.declaracion="("+t+", , ,"+i+")\n("+g+","+n+", ,"+i+")\n";
    int num=0;
    Simbolo s=new Simbolo(i,t,n);
    Simbolo temp=null;
    if(PrincipalCompi.tabla_simbolos.isEmpty()){
        PrincipalCompi.tabla_simbolos.add(s);
        PrincipalCompi.gramatica="DECLARACION ::= Int:t Identificador:i Igual:g Numero:n P_coma\n\n"+PrincipalCompi.gramatica;
    }else{
        for(int it=0;it<PrincipalCompi.tabla_simbolos.size();it++){
            temp=PrincipalCompi.tabla_simbolos.get(it);
            if(temp.getNombre().equals(i)){
                PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" ya fue declarado anteriormente");
                num++;
                break;
            }
        }
        if(num==0){
            PrincipalCompi.tabla_simbolos.add(s);
            PrincipalCompi.gramatica="DECLARACION ::= Int:t Identificador:i Igual:g Numero:n P_coma\n\n"+PrincipalCompi.gramatica;
        }
    }
    :} |
    Int:t Identificador:i Igual:g Numero:n {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(iright+1)+"; falta un punto y coma al final de la sentencia");
    :} |
    Int:t Identificador:i Numero:n P_coma{:
    PrincipalCompi.err.add("Error sintáctico linea:"+(iright+1)+"; falta un signo de igual");
    :} |
    Int:t Igual:g Numero:n P_coma{:
    PrincipalCompi.err.add("Error sintáctico linea:"+(tright+1)+"; falta la declaración de un identificador");
    :} |


    Identificador:i Igual:g Numero:n P_coma{:
    PrincipalCompi.declaracion="("+g+","+n+", ,"+i+")\n";
    int num=0;
    Simbolo temp=null;
    if(PrincipalCompi.tabla_simbolos.isEmpty()){
        PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido declarado");
    }else{
        for(int it=0;it<PrincipalCompi.tabla_simbolos.size();it++){
            temp=PrincipalCompi.tabla_simbolos.get(it);
            if(temp.getNombre().equals(i)){
                if(temp.getTipo().toString().equals("int")){
                    temp.setValor(n);
                    num++;
                    PrincipalCompi.gramatica="DECLARACION ::= Identificador:i Igual:g Numero:n P_coma\n\n"+PrincipalCompi.gramatica;
                    break;
                }else{
                    PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no es de tipo entero");
                    num++;
                    break;
                }
            }
        }
        if(num==0){
            PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido declarado");
        }
    }
    :} |
    Identificador:i Igual:g Numero:n {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(iright+1)+"; falta un punto y coma al final de la sentencia");
    :} |
    Identificador:i Numero:n P_coma{:
    PrincipalCompi.err.add("Error sintáctico linea:"+(iright+1)+"; falta un signo de igual");
    :} |
    /*Igual:g Numero:n P_coma{:
    PrincipalCompi.err.add("Error sintáctico linea:"+(iright+1)+"; falta un identificador declarado");
    :} |*/


    Bool:t Identificador:i Igual:g Op_booleano:o P_coma{:
    PrincipalCompi.declaracion="("+t+", , ,"+i+")\n("+g+","+o+", ,"+i+")\n";
    int num=0;
    Simbolo s=new Simbolo(i,t,o);
    Simbolo temp=null;
    if(PrincipalCompi.tabla_simbolos.isEmpty()){
        PrincipalCompi.tabla_simbolos.add(s);
        PrincipalCompi.gramatica="DECLARACION ::= Bool:t Identificador:i Igual:g Op_booleano:o P_coma\n\n"+PrincipalCompi.gramatica;
    }else{
        for(int it=0;it<PrincipalCompi.tabla_simbolos.size();it++){
            temp=PrincipalCompi.tabla_simbolos.get(it);
            if(temp.getNombre().equals(i)){
                PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" ya fue declarado anteriormente");
                num++;
                break;
            }
        }
        if(num==0){
            PrincipalCompi.tabla_simbolos.add(s);
            PrincipalCompi.gramatica="DECLARACION ::= Bool:t Identificador:i Igual:g Op_booleano:o P_coma\n\n"+PrincipalCompi.gramatica;
        }
    }
    :} |
    Bool:t Identificador:i Igual:g Op_booleano:o {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(iright+1)+"; falta un punto y coma al final de la sentencia");
    :} |
    Bool:t Identificador:i Op_booleano:o P_coma{:
    PrincipalCompi.err.add("Error sintáctico linea:"+(iright+1)+"; falta un signo de igual");
    :} |
    Bool:t Igual:g Op_booleano:o P_coma{:
    PrincipalCompi.err.add("Error sintáctico linea:"+(tright+1)+"; falta la declaración de un identificador");
    :} |


    Identificador:i Igual:g Op_booleano:o P_coma{:
    PrincipalCompi.declaracion="("+g+","+o+", ,"+i+")\n";
    int num=0;
    Simbolo temp=null;
    if(PrincipalCompi.tabla_simbolos.isEmpty()){
        PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido declarado");
    }else{
        for(int it=0;it<PrincipalCompi.tabla_simbolos.size();it++){
            temp=PrincipalCompi.tabla_simbolos.get(it);
            if(temp.getNombre().equals(i)){
                if(temp.getTipo().toString().equals("bool")){
                    temp.setValor(o);
                    num++;
                    PrincipalCompi.gramatica="DECLARACION ::= Identificador:i Igual:g Op_booleano:o P_coma\n\n"+PrincipalCompi.gramatica;
                    break;
                }else{
                    PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no es de tipo bool");
                    num++;
                    break;
                }
            }
        }
        if(num==0){
            PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido declarado");
        }
    }
    :} |
    Identificador:i Igual:g Op_booleano:o {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(iright+1)+"; falta un punto y coma al final de la sentencia");
    :} |
    Identificador:i Op_booleano:o P_coma{:
    PrincipalCompi.err.add("Error sintáctico linea:"+(iright+1)+"; falta un signo de igual");
    :} |
    /*Igual:g Op_booleano:o P_coma{:
    PrincipalCompi.err.add("Error sintáctico linea:"+(iright+1)+"; falta un identificador declarado");
    :} |*/


    SpinCraneLeft:a Parentesis_a SENTENCIA_ARITMETICA Parentesis_c P_coma {:
    PrincipalCompi.declaracion=PrincipalCompi.s_arit+"("+a+",TA"+PrincipalCompi.temp+", , )\n";
    PrincipalCompi.temp++;
    PrincipalCompi.s_arit="";
    PrincipalCompi.value=null;
    PrincipalCompi.gramatica="DECLARACION ::= SpinCraneLeft:a Parentesis_a SENTENCIA_ARITMETICA Parentesis_c P_coma\n\n"+PrincipalCompi.gramatica;
    :} |
    SpinCraneLeft:a Parentesis_a SENTENCIA_ARITMETICA Parentesis_c {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un punto y coma al final de la sentencia");
    :} |
    SpinCraneLeft:a Parentesis_a SENTENCIA_ARITMETICA P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un paréntesis de cierre");
    :} |
    SpinCraneLeft:a Parentesis_a Parentesis_c P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un argumento");
    :} |
    SpinCraneLeft:a SENTENCIA_ARITMETICA Parentesis_c P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un paréntesis de apertura");
    :} |
    Identificador:a Parentesis_a SENTENCIA_ARITMETICA Parentesis_c P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; método desconocido");
    :} |
    Identificador:a Parentesis_a SENTENCIA_ARITMETICA Parentesis_c {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; método desconocido");
    :} |
    Identificador:a Parentesis_a SENTENCIA_ARITMETICA P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; método desconocido");
    :} |
    Identificador:a Parentesis_a Parentesis_c P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; método desconocido");
    :} |
    Identificador:a SENTENCIA_ARITMETICA Parentesis_c P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; método desconocido");
    :} |


    SpinCraneLeft:a Parentesis_a Identificador:i Parentesis_c P_coma {:
    PrincipalCompi.declaracion="("+a+","+i+", , )\n";
    int n=0;
    Simbolo temp=null;
    if(PrincipalCompi.tabla_simbolos.isEmpty()){
        PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido declarado");
    }else{
        for(int it=0;it<PrincipalCompi.tabla_simbolos.size();it++){
            temp=PrincipalCompi.tabla_simbolos.get(it);
            if(temp.getNombre().equals(i)){
                if(temp.getTipo().toString().equals("int")){
                    if(temp.getValor()==null){
                        PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido inicializado");
                        n++;
                        break;
                    }else{
                        n++;
                        PrincipalCompi.gramatica="DECLARACION ::= SpinCraneLeft:a Parentesis_a Identificador:i Parentesis_c P_coma\n\n"+PrincipalCompi.gramatica;
                        break;
                    }
                }else{
                    PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no es de tipo int");
                    n++;
                    break;
                }
            }
        }
        if(n==0){
            PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido declarado");
        }
    }
    :} |
    SpinCraneLeft:a Parentesis_a Identificador:i Parentesis_c {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un punto y coma al final de la sentencia");
    :} |
    SpinCraneLeft:a Parentesis_a Identificador:i P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un paréntesis de cierre");
    :} |
    SpinCraneLeft:a Identificador:i Parentesis_c P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un paréntesis de apertura");
    :} |
    Identificador:a Parentesis_a Identificador:i Parentesis_c P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; método desconocido");
    :} |
    Identificador:a Parentesis_a Identificador:i Parentesis_c {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; método desconocido");
    :} |
    Identificador:a Parentesis_a Identificador:i P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; método desconocido");
    :} |
    Identificador:a Identificador:i Parentesis_c P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; método desconocido");
    :} |


    SpinCraneLeft:a Parentesis_a Numero:i Parentesis_c P_coma {:
    PrincipalCompi.declaracion="("+a+","+i+", , )\n";
    PrincipalCompi.gramatica="DECLARACION ::= SpinCraneLeft:a Parentesis_a Numero:i Parentesis_c P_coma\n\n"+PrincipalCompi.gramatica;
    :} |
    SpinCraneLeft:a Parentesis_a Numero:i Parentesis_c {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un punto y coma al final de la sentencia");
    :} |
    SpinCraneLeft:a Parentesis_a Numero:i P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un paréntesis de cierre");
    :} |
    SpinCraneLeft:a Numero:i Parentesis_c P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un paréntesis de apertura");
    :} |
    Identificador:a Parentesis_a Numero:i Parentesis_c P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; método desconocido");
    :} |
    Identificador:a Parentesis_a Numero:i Parentesis_c {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; método desconocido");
    :} |
    Identificador:a Parentesis_a Numero:i P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; método desconocido");
    :} |
    Identificador:a Numero:i Parentesis_c P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; método desconocido");
    :} |


    SpinCraneRight:a Parentesis_a SENTENCIA_ARITMETICA Parentesis_c P_coma {:
    PrincipalCompi.declaracion=PrincipalCompi.s_arit+"("+a+",TA"+PrincipalCompi.temp+", , )\n";
    PrincipalCompi.temp++;
    PrincipalCompi.s_arit="";
    PrincipalCompi.value=null;
    PrincipalCompi.gramatica="DECLARACION ::= SpinCraneRight:a Parentesis_a SENTENCIA_ARITMETICA Parentesis_c P_coma\n\n"+PrincipalCompi.gramatica;
    :} |
    SpinCraneRight:a Parentesis_a SENTENCIA_ARITMETICA Parentesis_c {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un punto y coma al final de la sentencia");
    :} |
    SpinCraneRight:a Parentesis_a SENTENCIA_ARITMETICA P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un paréntesis de cierre");
    :} |
    SpinCraneRight:a Parentesis_a Parentesis_c P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un argumento");
    :} |
    SpinCraneRight:a SENTENCIA_ARITMETICA Parentesis_c P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un paréntesis de apertura");
    :} |


    SpinCraneRight:a Parentesis_a Identificador:i Parentesis_c P_coma {:
    PrincipalCompi.declaracion="("+a+","+i+", , )\n";
    int n=0;
    Simbolo temp=null;
    if(PrincipalCompi.tabla_simbolos.isEmpty()){
        PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido declarado");
    }else{
        for(int it=0;it<PrincipalCompi.tabla_simbolos.size();it++){
            temp=PrincipalCompi.tabla_simbolos.get(it);
            if(temp.getNombre().equals(i)){
                if(temp.getTipo().toString().equals("int")){
                    if(temp.getValor()==null){
                        PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido inicializado");
                        n++;
                        break;
                    }else{
                        n++;
                        PrincipalCompi.gramatica="DECLARACION ::= SpinCraneRight:a Parentesis_a Identificador:i Parentesis_c P_coma\n\n"+PrincipalCompi.gramatica;
                        break;
                    }
                }else{
                    PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no es de tipo int");
                    n++;
                    break;
                }
            }
        }
        if(n==0){
            PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido declarado");
        }
    }
    :} |
    SpinCraneRight:a Parentesis_a Identificador:i Parentesis_c {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un punto y coma al final de la sentencia");
    :} |
    SpinCraneRight:a Parentesis_a Identificador:i P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un paréntesis de cierre");
    :} |
    SpinCraneRight:a Identificador:i Parentesis_c P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un paréntesis de apertura");
    :} |


    SpinCraneRight:a Parentesis_a Numero:i Parentesis_c P_coma {:
    PrincipalCompi.declaracion="("+a+","+i+", , )\n";
    PrincipalCompi.gramatica="DECLARACION ::= SpinCraneRight:a Parentesis_a Numero:i Parentesis_c P_coma\n\n"+PrincipalCompi.gramatica;
    :} |
    SpinCraneRight:a Parentesis_a Numero:i Parentesis_c {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un punto y coma al final de la sentencia");
    :} |
    SpinCraneRight:a Parentesis_a Numero:i P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un paréntesis de cierre");
    :} |
    SpinCraneRight:a Numero:i Parentesis_c P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un paréntesis de apertura");
    :} |


    MoveFowardCrane:a Parentesis_a SENTENCIA_ARITMETICA Parentesis_c P_coma {:
    PrincipalCompi.declaracion=PrincipalCompi.s_arit+"("+a+",TA"+PrincipalCompi.temp+", , )\n";
    PrincipalCompi.temp++;
    PrincipalCompi.s_arit="";
    PrincipalCompi.value=null;
    PrincipalCompi.gramatica="DECLARACION ::= MoveFowardCrane:a Parentesis_a SENTENCIA_ARITMETICA Parentesis_c P_coma\n\n"+PrincipalCompi.gramatica;
    :} |
    MoveFowardCrane:a Parentesis_a SENTENCIA_ARITMETICA Parentesis_c {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un punto y coma al final de la sentencia");
    :} |
    MoveFowardCrane:a Parentesis_a SENTENCIA_ARITMETICA P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un paréntesis de cierre");
    :} |
    MoveFowardCrane:a Parentesis_a Parentesis_c P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un argumento");
    :} |
    MoveFowardCrane:a SENTENCIA_ARITMETICA Parentesis_c P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un paréntesis de apertura");
    :} |


    MoveFowardCrane:a Parentesis_a Identificador:i Parentesis_c P_coma {:
    PrincipalCompi.declaracion="("+a+","+i+", , )\n";
    int n=0;
    Simbolo temp=null;
    if(PrincipalCompi.tabla_simbolos.isEmpty()){
        PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido declarado");
    }else{
        for(int it=0;it<PrincipalCompi.tabla_simbolos.size();it++){
            temp=PrincipalCompi.tabla_simbolos.get(it);
            if(temp.getNombre().equals(i)){
                if(temp.getTipo().toString().equals("int")){
                    if(temp.getValor()==null){
                        PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido inicializado");
                        n++;
                        break;
                    }else{
                        n++;
                        PrincipalCompi.gramatica="DECLARACION ::= MoveFowardCrane:a Parentesis_a Identificador:i Parentesis_c P_coma\n\n"+PrincipalCompi.gramatica;
                        break;
                    }
                }else{
                    PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no es de tipo int");
                    n++;
                    break;
                }
            }
        }
        if(n==0){
            PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido declarado");
        }
    }
    :} |
    MoveFowardCrane:a Parentesis_a Identificador:i Parentesis_c {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un punto y coma al final de la sentencia");
    :} |
    MoveFowardCrane:a Parentesis_a Identificador:i P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un paréntesis de cierre");
    :} |
    MoveFowardCrane:a Identificador:i Parentesis_c P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un paréntesis de apertura");
    :} |


    MoveFowardCrane:a Parentesis_a Numero:i Parentesis_c P_coma {:
    PrincipalCompi.declaracion="("+a+","+i+", , )\n";
    PrincipalCompi.gramatica="DECLARACION ::= MoveFowardCrane:a Parentesis_a Numero:i Parentesis_c P_coma\n\n"+PrincipalCompi.gramatica;
    :} |
    MoveFowardCrane:a Parentesis_a Numero:i Parentesis_c {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un punto y coma al final de la sentencia");
    :} |
    MoveFowardCrane:a Parentesis_a Numero:i P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un paréntesis de cierre");
    :} |
    MoveFowardCrane:a Numero:i Parentesis_c P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un paréntesis de apertura");
    :} |


    MoveBackCrane:a Parentesis_a SENTENCIA_ARITMETICA Parentesis_c P_coma {:
    PrincipalCompi.declaracion=PrincipalCompi.s_arit+"("+a+",TA"+PrincipalCompi.temp+", , )\n";
    PrincipalCompi.temp++;
    PrincipalCompi.s_arit="";
    PrincipalCompi.value=null;
    PrincipalCompi.gramatica="DECLARACION ::= MoveBackCrane:a Parentesis_a SENTENCIA_ARITMETICA Parentesis_c P_coma\n\n"+PrincipalCompi.gramatica;
    :} |
    MoveBackCrane:a Parentesis_a SENTENCIA_ARITMETICA Parentesis_c {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un punto y coma al final de la sentencia");
    :} |
    MoveBackCrane:a Parentesis_a SENTENCIA_ARITMETICA P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un paréntesis de cierre");
    :} |
    MoveBackCrane:a Parentesis_a Parentesis_c P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un argumento");
    :} |
    MoveBackCrane:a SENTENCIA_ARITMETICA Parentesis_c P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un paréntesis de apertura");
    :} |


    MoveBackCrane:a Parentesis_a Identificador:i Parentesis_c P_coma {:
    PrincipalCompi.declaracion="("+a+","+i+", , )\n";
    int n=0;
    Simbolo temp=null;
    if(PrincipalCompi.tabla_simbolos.isEmpty()){
        PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido declarado");
    }else{
        for(int it=0;it<PrincipalCompi.tabla_simbolos.size();it++){
            temp=PrincipalCompi.tabla_simbolos.get(it);
            if(temp.getNombre().equals(i)){
                if(temp.getTipo().toString().equals("int")){
                    if(temp.getValor()==null){
                        PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido inicializado");
                        n++;
                        break;
                    }else{
                        n++;
                        PrincipalCompi.gramatica="DECLARACION ::= MoveBackCrane:a Parentesis_a Identificador:i Parentesis_c P_coma\n\n"+PrincipalCompi.gramatica;
                        break;
                    }
                }else{
                    PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no es de tipo int");
                    n++;
                    break;
                }
            }
        }
        if(n==0){
            PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido declarado");
        }
    }
    :} |
    MoveBackCrane:a Parentesis_a Identificador:i Parentesis_c {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un punto y coma al final de la sentencia");
    :} |
    MoveBackCrane:a Parentesis_a Identificador:i P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un paréntesis de cierre");
    :} |
    MoveBackCrane:a Identificador:i Parentesis_c P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un paréntesis de apertura");
    :} |


    MoveBackCrane:a Parentesis_a Numero:i Parentesis_c P_coma {:
    PrincipalCompi.declaracion="("+a+","+i+", , )\n";
    PrincipalCompi.gramatica="DECLARACION ::= MoveBackCrane:a Parentesis_a Numero:i Parentesis_c P_coma\n\n"+PrincipalCompi.gramatica;
    :} |
    MoveBackCrane:a Parentesis_a Numero:i Parentesis_c {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un punto y coma al final de la sentencia");
    :} |
    MoveBackCrane:a Parentesis_a Numero:i P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un paréntesis de cierre");
    :} |
    MoveBackCrane:a Numero:i Parentesis_c P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un paréntesis de apertura");
    :} |


    SpinBallLeft:a Parentesis_a SENTENCIA_ARITMETICA Parentesis_c P_coma {:
    PrincipalCompi.declaracion=PrincipalCompi.s_arit+"("+a+",TA"+PrincipalCompi.temp+", , )\n";
    PrincipalCompi.temp++;
    PrincipalCompi.s_arit="";
    PrincipalCompi.value=null;
    PrincipalCompi.gramatica="DECLARACION ::= SpinBallLeft:a Parentesis_a SENTENCIA_ARITMETICA Parentesis_c P_coma\n\n"+PrincipalCompi.gramatica;
    :} |
    SpinBallLeft:a Parentesis_a SENTENCIA_ARITMETICA Parentesis_c {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un punto y coma al final de la sentencia");
    :} |
    SpinBallLeft:a Parentesis_a SENTENCIA_ARITMETICA P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un paréntesis de cierre");
    :} |
    SpinBallLeft:a Parentesis_a Parentesis_c P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un argumento");
    :} |
    SpinBallLeft:a SENTENCIA_ARITMETICA Parentesis_c P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un paréntesis de apertura");
    :} |


    SpinBallLeft:a Parentesis_a Identificador:i Parentesis_c P_coma {:
    PrincipalCompi.declaracion="("+a+","+i+", , )\n";
    int n=0;
    Simbolo temp=null;
    if(PrincipalCompi.tabla_simbolos.isEmpty()){
        PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido declarado");
    }else{
        for(int it=0;it<PrincipalCompi.tabla_simbolos.size();it++){
            temp=PrincipalCompi.tabla_simbolos.get(it);
            if(temp.getNombre().equals(i)){
                if(temp.getTipo().toString().equals("int")){
                    if(temp.getValor()==null){
                        PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido inicializado");
                        n++;
                        break;
                    }else{
                        n++;
                        PrincipalCompi.gramatica="DECLARACION ::= SpinBallLeft:a Parentesis_a Identificador:i Parentesis_c P_coma\n\n"+PrincipalCompi.gramatica;
                        break;
                    }
                }else{
                    PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no es de tipo int");
                    n++;
                    break;
                }
            }
        }
        if(n==0){
            PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido declarado");
        }
    }
    :} |
    SpinBallLeft:a Parentesis_a Identificador:i Parentesis_c {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un punto y coma al final de la sentencia");
    :} |
    SpinBallLeft:a Parentesis_a Identificador:i P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un paréntesis de cierre");
    :} |
    SpinBallLeft:a Identificador:i Parentesis_c P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un paréntesis de apertura");
    :} |


    SpinBallLeft:a Parentesis_a Numero:i Parentesis_c P_coma {:
    PrincipalCompi.declaracion="("+a+","+i+", , )\n";
    PrincipalCompi.gramatica="DECLARACION ::= SpinBallLeft:a Parentesis_a Numero:i Parentesis_c P_coma\n\n"+PrincipalCompi.gramatica;
    :} |
    SpinBallLeft:a Parentesis_a Numero:i Parentesis_c {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un punto y coma al final de la sentencia");
    :} |
    SpinBallLeft:a Parentesis_a Numero:i P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un paréntesis de cierre");
    :} |
    SpinBallLeft:a Numero:i Parentesis_c P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un paréntesis de apertura");
    :} |


    SpinBallRight:a Parentesis_a SENTENCIA_ARITMETICA Parentesis_c P_coma {:
    PrincipalCompi.declaracion=PrincipalCompi.s_arit+"("+a+",TA"+PrincipalCompi.temp+", , )\n";
    PrincipalCompi.temp++;
    PrincipalCompi.s_arit="";
    PrincipalCompi.value=null;
    PrincipalCompi.gramatica="DECLARACION ::= SpinBallRight:a Parentesis_a SENTENCIA_ARITMETICA Parentesis_c P_coma\n\n"+PrincipalCompi.gramatica;
    :} |
    SpinBallRight:a Parentesis_a SENTENCIA_ARITMETICA Parentesis_c {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un punto y coma al final de la sentencia");
    :} |
    SpinBallRight:a Parentesis_a SENTENCIA_ARITMETICA P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un paréntesis de cierre");
    :} |
    SpinBallRight:a Parentesis_a Parentesis_c P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un argumento");
    :} |
    SpinBallRight:a SENTENCIA_ARITMETICA Parentesis_c P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un paréntesis de apertura");
    :} |


    SpinBallRight:a Parentesis_a Identificador:i Parentesis_c P_coma {:
    PrincipalCompi.declaracion="("+a+","+i+", , )\n";
    int n=0;
    Simbolo temp=null;
    if(PrincipalCompi.tabla_simbolos.isEmpty()){
        PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido declarado");
    }else{
        for(int it=0;it<PrincipalCompi.tabla_simbolos.size();it++){
            temp=PrincipalCompi.tabla_simbolos.get(it);
            if(temp.getNombre().equals(i)){
                if(temp.getTipo().toString().equals("int")){
                    if(temp.getValor()==null){
                        PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido inicializado");
                        n++;
                        break;
                    }else{
                        n++;
                        PrincipalCompi.gramatica="DECLARACION ::= SpinBallRight:a Parentesis_a Identificador:i Parentesis_c P_coma\n\n"+PrincipalCompi.gramatica;
                        break;
                    }
                }else{
                    PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no es de tipo int");
                    n++;
                    break;
                }
            }
        }
        if(n==0){
            PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido declarado");
        }
    }
    :} |
    SpinBallRight:a Parentesis_a Identificador:i Parentesis_c {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un punto y coma al final de la sentencia");
    :} |
    SpinBallRight:a Parentesis_a Identificador:i P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un paréntesis de cierre");
    :} |
    SpinBallRight:a Identificador:i Parentesis_c P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un paréntesis de apertura");
    :} |


    SpinBallRight:a Parentesis_a Numero:i Parentesis_c P_coma {:
    PrincipalCompi.declaracion="("+a+","+i+", , )\n";
    PrincipalCompi.gramatica="DECLARACION ::= SpinBallRight:a Parentesis_a Numero:i Parentesis_c P_coma\n\n"+PrincipalCompi.gramatica;
    :} |
    SpinBallRight:a Parentesis_a Numero:i Parentesis_c {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un punto y coma al final de la sentencia");
    :} |
    SpinBallRight:a Parentesis_a Numero:i P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un paréntesis de cierre");
    :} |
    SpinBallRight:a Numero:i Parentesis_c P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un paréntesis de apertura");
    :} |


    HitToTheLeft:a Parentesis_a Parentesis_c P_coma {:
    PrincipalCompi.declaracion="("+a+", , , )\n";
    PrincipalCompi.gramatica="DECLARACION ::= HitToTheLeft:a Parentesis_a Parentesis_c P_coma\n\n"+PrincipalCompi.gramatica;
    :} |
    HitToTheLeft:a Parentesis_a Parentesis_c {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un punto y coma al final de la sentencia");
    :} |
    HitToTheLeft:a Parentesis_a P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un paréntesis de cierre");
    :} |
    HitToTheLeft:a Parentesis_c P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un paréntesis de apertura");
    :} |


    HitToTheRight:a Parentesis_a Parentesis_c P_coma {:
    PrincipalCompi.declaracion="("+a+", , , )\n";
    PrincipalCompi.gramatica="DECLARACION ::= HitToTheRight:a Parentesis_a Parentesis_c P_coma\n\n"+PrincipalCompi.gramatica;
    :} |
    HitToTheRight:a Parentesis_a Parentesis_c {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un punto y coma al final de la sentencia");
    :} |
    HitToTheRight:a Parentesis_a P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un paréntesis de cierre");
    :} |
    HitToTheRight:a Parentesis_c P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un paréntesis de apertura");
    :} |


    StopLoop P_coma {:
    PrincipalCompi.declaracion="(jmp loop"+PrincipalCompi.loop+":, , , )\n";
    PrincipalCompi.gramatica="DECLARACION ::= StopLoop P_coma\n\n"+PrincipalCompi.gramatica;
    :} |
    StopLoop:a {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un punto y coma al final de la sentencia");
    :} |


    WaitTime:a Parentesis_a SENTENCIA_ARITMETICA Parentesis_c P_coma {:
    PrincipalCompi.declaracion=PrincipalCompi.s_arit+"("+a+",TA"+PrincipalCompi.temp+", , )\n";
    PrincipalCompi.temp++;
    PrincipalCompi.s_arit="";
    PrincipalCompi.value=null;
    PrincipalCompi.gramatica="DECLARACION ::= WaitTime:a Parentesis_a SENTENCIA_ARITMETICA Parentesis_c P_coma\n\n"+PrincipalCompi.gramatica;
    :} |
    WaitTime:a Parentesis_a SENTENCIA_ARITMETICA Parentesis_c {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un punto y coma al final de la sentencia");
    :} |
    WaitTime:a Parentesis_a SENTENCIA_ARITMETICA P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un paréntesis de cierre");
    :} |
    WaitTime:a Parentesis_a Parentesis_c P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un argumento");
    :} |
    WaitTime:a SENTENCIA_ARITMETICA Parentesis_c P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un paréntesis de apertura");
    :} |


    WaitTime:a Parentesis_a Identificador:i Parentesis_c P_coma {:
    PrincipalCompi.declaracion="("+a+","+i+", , )\n";
    int n=0;
    Simbolo temp=null;
    if(PrincipalCompi.tabla_simbolos.isEmpty()){
        PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido declarado");
    }else{
        for(int it=0;it<PrincipalCompi.tabla_simbolos.size();it++){
            temp=PrincipalCompi.tabla_simbolos.get(it);
            if(temp.getNombre().equals(i)){
                if(temp.getTipo().toString().equals("int")){
                    if(temp.getValor()==null){
                        PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido inicializado");
                        n++;
                        break;
                    }else{
                        n++;
                        PrincipalCompi.gramatica="DECLARACION ::= WaitTime:a Parentesis_a Identificador:i Parentesis_c P_coma\n\n"+PrincipalCompi.gramatica;
                        break;
                    }
                }else{
                    PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no es de tipo int");
                    n++;
                    break;
                }
            }
        }
        if(n==0){
            PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido declarado");
        }
    }
    :} |
    WaitTime:a Parentesis_a Identificador:i Parentesis_c {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un punto y coma al final de la sentencia");
    :} |
    WaitTime:a Parentesis_a Identificador:i P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un paréntesis de cierre");
    :} |
    WaitTime:a Identificador:i Parentesis_c P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un paréntesis de apertura");
    :} |


    WaitTime:a Parentesis_a Numero:i Parentesis_c P_coma {:
    PrincipalCompi.declaracion="("+a+","+i+", , )\n";
    PrincipalCompi.gramatica="DECLARACION ::= WaitTime:a Parentesis_a Numero:i Parentesis_c P_coma\n\n"+PrincipalCompi.gramatica;
    :} |
    WaitTime:a Parentesis_a Numero:i Parentesis_c {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un punto y coma al final de la sentencia");
    :} |
    WaitTime:a Parentesis_a Numero:i P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un paréntesis de cierre");
    :} |
    WaitTime:a Numero:i Parentesis_c P_coma {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(aright+1)+"; falta un paréntesis de apertura");
    :}
    
;
IF ::= If Parentesis_a SENTENCIA_BOOLEANA Parentesis_c Llave_a SENTENCIA Llave_c {:
    PrincipalCompi.status--;
    PrincipalCompi.ifs=PrincipalCompi.s_bool;
    PrincipalCompi.ifs=PrincipalCompi.ifs+"(jf choice"+PrincipalCompi.choice+":,TB"+PrincipalCompi.tempb+", , )\n"+PrincipalCompi.sentencia[PrincipalCompi.status]+"choice"+PrincipalCompi.choice+":\n";
    PrincipalCompi.tempb++;
    PrincipalCompi.sentencia[PrincipalCompi.status]=PrincipalCompi.s_bool="";
    PrincipalCompi.choice++;
    PrincipalCompi.valueb=null;
    :}|
    /*If Parentesis_a SENTENCIA_BOOLEANA Parentesis_c Llave_a SENTENCIA:s {:
    PrincipalCompi.err.add("Error sintáctico linea:"+(sright+1)+"; falta un paréntesis de cierre");
    :} |*/


    If Parentesis_a SENTENCIA_BOOLEANA Parentesis_c Llave_a Llave_c |


    If Parentesis_a Op_booleano:o Parentesis_c Llave_a SENTENCIA Llave_c {:
    PrincipalCompi.status--;
    PrincipalCompi.ifs=PrincipalCompi.ifs+"(jf choice"+PrincipalCompi.choice+":,"+o+", , )\n"+PrincipalCompi.sentencia[PrincipalCompi.status]+"choice"+PrincipalCompi.choice+":\n";
    PrincipalCompi.sentencia[PrincipalCompi.status]=PrincipalCompi.s_bool="";
    PrincipalCompi.choice++;
    :}|
    If Parentesis_a Identificador:i Parentesis_c Llave_a SENTENCIA Llave_c {:
    PrincipalCompi.status--;
    PrincipalCompi.ifs=PrincipalCompi.ifs+"(jf choice"+PrincipalCompi.choice+":,"+i+", , )\n"+PrincipalCompi.sentencia[PrincipalCompi.status]+"choice"+PrincipalCompi.choice+":\n";
    PrincipalCompi.sentencia[PrincipalCompi.status]=PrincipalCompi.s_bool="";
    PrincipalCompi.choice++;
    Simbolo a=null;
        for(int it=0;it<PrincipalCompi.tabla_simbolos.size();it++){
            if(i.equals(PrincipalCompi.tabla_simbolos.get(it).getNombre().toString())){
                a=PrincipalCompi.tabla_simbolos.get(it);
            }
        }
        if(a==null){
            PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido declarado");
        }else{
            if(!a.getTipo().toString().equals("bool")){
                PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no es de tipo bool");
            }else{
                if(a.getValor()==null){
                    PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido inicializado");
                }
            }
        }
    :}|
    If Parentesis_a SENTENCIA_BOOLEANA Parentesis_c Llave_a SENTENCIA Llave_c ELSE {:
    PrincipalCompi.status--;
    PrincipalCompi.ifs=PrincipalCompi.s_bool;
    PrincipalCompi.ifs=PrincipalCompi.ifs+"(jf choice"+PrincipalCompi.choice+":,TB"+PrincipalCompi.tempb+", , )\n"+PrincipalCompi.sentencia[PrincipalCompi.status]+"(jmp choice"+PrincipalCompi.choice+":, , , )\n"+"choice"+(PrincipalCompi.choice+1)+":\n";
    PrincipalCompi.tempb++;
    PrincipalCompi.choice++;
    PrincipalCompi.ifs=PrincipalCompi.ifs+PrincipalCompi.elses+"choice"+PrincipalCompi.choice+":\n";
    PrincipalCompi.sentencia[PrincipalCompi.status]=PrincipalCompi.s_bool=PrincipalCompi.elses="";
    PrincipalCompi.choice++;
    PrincipalCompi.valueb=null;
    :}|
    If Parentesis_a Op_booleano:o Parentesis_c Llave_a SENTENCIA Llave_c ELSE {:
    PrincipalCompi.status--;
    PrincipalCompi.ifs=PrincipalCompi.ifs+"(jf choice"+PrincipalCompi.choice+":,"+o+", , )\n"+PrincipalCompi.sentencia[PrincipalCompi.status]+"(jmp choice"+(PrincipalCompi.choice+1)+":, , , )\n"+"choice"+PrincipalCompi.choice+":\n";
    PrincipalCompi.tempb++;
    PrincipalCompi.choice++;
    PrincipalCompi.ifs=PrincipalCompi.ifs+PrincipalCompi.elses+"choice"+PrincipalCompi.choice+":\n";
    PrincipalCompi.sentencia[PrincipalCompi.status]=PrincipalCompi.s_bool=PrincipalCompi.elses="";
    PrincipalCompi.choice++;
    :} |
    If Parentesis_a Identificador:i Parentesis_c Llave_a SENTENCIA Llave_c ELSE {:
    PrincipalCompi.status--;
    PrincipalCompi.ifs=PrincipalCompi.ifs+"(jf choice"+PrincipalCompi.choice+":,"+i+", , )\n"+PrincipalCompi.sentencia[PrincipalCompi.status]+"(jmp choice"+(PrincipalCompi.choice+1)+":, , , )\n"+"choice"+PrincipalCompi.choice+":\n";
    PrincipalCompi.choice++;
    PrincipalCompi.ifs=PrincipalCompi.ifs+PrincipalCompi.elses+"choice"+PrincipalCompi.choice+":\n";
    PrincipalCompi.sentencia[PrincipalCompi.status]=PrincipalCompi.s_bool=PrincipalCompi.elses="";
    PrincipalCompi.choice++;
    Simbolo a=null;
        for(int it=0;it<PrincipalCompi.tabla_simbolos.size();it++){
            if(i.equals(PrincipalCompi.tabla_simbolos.get(it).getNombre().toString())){
                a=PrincipalCompi.tabla_simbolos.get(it);
            }
        }
        if(a==null){
            PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido declarado");
        }else{
            if(!a.getTipo().toString().equals("bool")){
                PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no es de tipo bool");
            }else{
                if(a.getValor()==null){
                    PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido inicializado");
                }
            }
        }
    :}
;
ELSE ::=Else Llave_a SENTENCIA Llave_c {:
    PrincipalCompi.status--;
    PrincipalCompi.elses=PrincipalCompi.sentencia[PrincipalCompi.status];
    :}
;
SENTENCIA_BOOLEANA ::=  
    Identificador:i Op_relacional:o Op_booleano:b {:
    PrincipalCompi.s_bool="("+o+","+i+","+b+",TB"+PrincipalCompi.tempb+")\n";
    Simbolo a=null;
    for(int it=0;it<PrincipalCompi.tabla_simbolos.size();it++){
        if(i.equals(PrincipalCompi.tabla_simbolos.get(it).getNombre())){
            a=PrincipalCompi.tabla_simbolos.get(it);
        }
    }
    if(a==null){
        PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido declarado");
    }else{
        if(!a.getTipo().toString().equals("bool")){
            PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no es de tipo bool");
        }else{
            if(a.getValor()==null){
                PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido inicializado");
            }else{
                switch(o.toString()){
                    case "==": PrincipalCompi.valueb=(Boolean.parseBoolean(a.getValor().toString()) && Boolean.parseBoolean(b.toString()));break;
                    case "!=": PrincipalCompi.valueb=(Boolean.parseBoolean(a.getValor().toString()) != Boolean.parseBoolean(b.toString()));break;
                    default:
                        PrincipalCompi.err.add("Error semántico linea:"+(oright+1)+"; el operador "+o+" no es válido");
                        break;
                }
            }
        }
    }
    :}|
    Op_booleano:b Op_relacional:o Identificador:i {:
    PrincipalCompi.s_bool="("+o+","+b+","+i+",TB"+PrincipalCompi.tempb+")\n";
    Simbolo a=null;
    for(int it=0;it<PrincipalCompi.tabla_simbolos.size();it++){
        if(i.equals(PrincipalCompi.tabla_simbolos.get(it).getNombre().toString())){
            a=PrincipalCompi.tabla_simbolos.get(it);
        }
    }
    if(a==null){
        PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido declarado");
    }else{
        if(!a.getTipo().toString().equals("bool")){
            PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no es de tipo bool");
        }else{
            if(a.getValor()==null){
                PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido inicializado");
            }else{
                switch(o.toString()){
                    case "==": PrincipalCompi.valueb=(Boolean.parseBoolean(a.getValor().toString()) && Boolean.parseBoolean(b.toString()));break;
                    case "!=": PrincipalCompi.valueb=(Boolean.parseBoolean(a.getValor().toString()) != Boolean.parseBoolean(b.toString()));break;
                    default:
                        PrincipalCompi.err.add("Error semántico linea:"+(oright+1)+"; el operador "+o+" no es válido");
                        break;
                }
            }
        }
    }
    :}|
    Identificador:i Op_relacional:o SENTENCIA_ARITMETICA {:
    PrincipalCompi.s_bool=PrincipalCompi.s_arit+"("+o+","+i+",TA"+PrincipalCompi.temp+",TB"+PrincipalCompi.tempb+")\n";
    PrincipalCompi.temp++;
    Simbolo a=null;
    for(int it=0;it<PrincipalCompi.tabla_simbolos.size();it++){
        if(i.equals(PrincipalCompi.tabla_simbolos.get(it).getNombre().toString())){
            a=PrincipalCompi.tabla_simbolos.get(it);
        }
    }
    if(a==null){
        PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido declarado");
    }else{
        if(!a.getTipo().toString().equals("int")){
            PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no es de tipo int");
        }else{
            if(a.getValor()==null){
                PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido inicializado");
            }else{
                if(PrincipalCompi.value!=null){
                    switch(o.toString()){
                        case ">":PrincipalCompi.valueb=Integer.parseInt(a.getValor().toString())>Integer.parseInt(PrincipalCompi.value.toString());break;
                        case "<":PrincipalCompi.valueb=Integer.parseInt(a.getValor().toString())<Integer.parseInt(PrincipalCompi.value.toString());break;
                        case "==":PrincipalCompi.valueb=Integer.parseInt(a.getValor().toString())==Integer.parseInt(PrincipalCompi.value.toString());break;
                        case "!=": PrincipalCompi.valueb=Integer.parseInt(a.getValor().toString())!=Integer.parseInt(PrincipalCompi.value.toString());break;
                        case ">=": PrincipalCompi.valueb=Integer.parseInt(a.getValor().toString())>=Integer.parseInt(PrincipalCompi.value.toString());break;
                        case "<=": PrincipalCompi.valueb=Integer.parseInt(a.getValor().toString())<=Integer.parseInt(PrincipalCompi.value.toString());break;
                        case ">>": PrincipalCompi.valueb=Integer.parseInt(a.getValor().toString())>Integer.parseInt(PrincipalCompi.value.toString());break;
                        case "<<": PrincipalCompi.valueb=Integer.parseInt(a.getValor().toString())>Integer.parseInt(PrincipalCompi.value.toString());break;
                        default:break;
                    }
                    PrincipalCompi.value=null;
                }
            }
        }
    }
    :}|
    SENTENCIA_ARITMETICA Op_relacional:o Identificador:i {:
    PrincipalCompi.s_bool=PrincipalCompi.s_arit+"("+o+",TA"+PrincipalCompi.temp+","+i+",TB"+PrincipalCompi.tempb+")\n";
    PrincipalCompi.temp++;
    Simbolo a=null;
    for(int it=0;it<PrincipalCompi.tabla_simbolos.size();it++){
        if(i.equals(PrincipalCompi.tabla_simbolos.get(it).getNombre())){
            a=PrincipalCompi.tabla_simbolos.get(it);
        }
    }
    if(a==null){
        PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido declarado");
    }else{
        if(!a.getTipo().toString().equals("int")){
            PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no es de tipo int");
        }else{
            if(a.getValor()==null){
                PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido inicializado");
            }else{
                if(PrincipalCompi.value!=null){
                    switch(o.toString()){
                        case ">":PrincipalCompi.valueb=Integer.parseInt(PrincipalCompi.value.toString())>Integer.parseInt(a.getValor().toString());break;
                        case "<":PrincipalCompi.valueb=Integer.parseInt(PrincipalCompi.value.toString())<Integer.parseInt(a.getValor().toString());break;
                        case "==":PrincipalCompi.valueb=Integer.parseInt(PrincipalCompi.value.toString())==Integer.parseInt(a.getValor().toString());break;
                        case "!=": PrincipalCompi.valueb=Integer.parseInt(PrincipalCompi.value.toString())!=Integer.parseInt(a.getValor().toString());break;
                        case ">=": PrincipalCompi.valueb=Integer.parseInt(PrincipalCompi.value.toString())>=Integer.parseInt(a.getValor().toString());break;
                        case "<=": PrincipalCompi.valueb=Integer.parseInt(PrincipalCompi.value.toString())<=Integer.parseInt(a.getValor().toString());break;
                        case ">>": PrincipalCompi.valueb=Integer.parseInt(PrincipalCompi.value.toString())>Integer.parseInt(a.getValor().toString());break;
                        case "<<": PrincipalCompi.valueb=Integer.parseInt(PrincipalCompi.value.toString())<Integer.parseInt(a.getValor().toString());break;
                        default:break;
                    }
                    PrincipalCompi.value=null;
                }
            }
        }
    }
    :}|
    Identificador:i Op_relacional:o Identificador:n {:
    PrincipalCompi.s_bool=PrincipalCompi.s_arit+"("+o+","+i+","+n+",TB"+PrincipalCompi.tempb+")\n";
    Simbolo a=null;
    Simbolo b=null;
    for(int it=0;it<PrincipalCompi.tabla_simbolos.size();it++){
        if(i.equals(PrincipalCompi.tabla_simbolos.get(it).getNombre().toString())){
            a=PrincipalCompi.tabla_simbolos.get(it);
        }
        if(n.equals(PrincipalCompi.tabla_simbolos.get(it).getNombre().toString())){
            b=PrincipalCompi.tabla_simbolos.get(it);
        }
    }
    if(a==null || b==null){
        if(a==null){
            PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido declarado");
        }
        if(b==null){
            PrincipalCompi.err.add("Error semántico linea:"+(nright+1)+"; el identificador "+n+" no ha sido declarado");
        }
    }else{
        if(!a.getTipo().toString().equals("int")||!b.getTipo().toString().equals("int")){
            if(!a.getTipo().toString().equals("int")){
                PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no es de tipo int");
            }
            if(!b.getTipo().toString().equals("int")){
                PrincipalCompi.err.add("Error semántico linea:"+(nright+1)+"; el identificador "+n+" no es de tipo int");
            }
        }else{
            if(a.getValor()==null||b.getValor()==null){
                if(a.getValor()==null){
                    PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido inicializado");
                }
                if(b.getValor()==null){
                    PrincipalCompi.err.add("Error semántico linea:"+(nright+1)+"; el identificador "+n+" no ha sido inicializado");
                }
            }else{
                switch(o.toString()){
                    case ">":PrincipalCompi.valueb=Integer.parseInt(a.getValor().toString())>Integer.parseInt(b.getValor().toString());break;
                    case "<":PrincipalCompi.valueb=Integer.parseInt(a.getValor().toString())<Integer.parseInt(b.getValor().toString());break;
                    case "==":PrincipalCompi.valueb=Integer.parseInt(a.getValor().toString())==Integer.parseInt(b.getValor().toString());break;
                    case "!=": PrincipalCompi.valueb=Integer.parseInt(a.getValor().toString())!=Integer.parseInt(b.getValor().toString());break;
                    case ">=": PrincipalCompi.valueb=Integer.parseInt(a.getValor().toString())>=Integer.parseInt(b.getValor().toString());break;
                    case "<=": PrincipalCompi.valueb=Integer.parseInt(a.getValor().toString())<=Integer.parseInt(b.getValor().toString());break;
                    case ">>": PrincipalCompi.valueb=Integer.parseInt(a.getValor().toString())>Integer.parseInt(b.getValor().toString());break;
                    case "<<": PrincipalCompi.valueb=Integer.parseInt(a.getValor().toString())<Integer.parseInt(b.getValor().toString());break;
                    default:break;
                }
            }
        }
    }
    :}|
    Identificador:i Op_relacional:o Numero:n {:
    PrincipalCompi.s_bool="("+o+","+i+","+n+",TB"+PrincipalCompi.tempb+")\n";
    PrincipalCompi.temp++;
    Simbolo a=null;
    for(int it=0;it<PrincipalCompi.tabla_simbolos.size();it++){
        if(i.equals(PrincipalCompi.tabla_simbolos.get(it).getNombre().toString())){
            a=PrincipalCompi.tabla_simbolos.get(it);
        }
    }
    if(a==null){
        PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido declarado");
    }else{
        if(!a.getTipo().toString().equals("int")){
            PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no es de tipo int");
        }else{
            if(a.getValor()==null){
                PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido inicializado");
            }else{
                switch(o.toString()){
                    case ">":PrincipalCompi.valueb=Integer.parseInt(a.getValor().toString())>Integer.parseInt(n.toString());break;
                    case "<":PrincipalCompi.valueb=Integer.parseInt(a.getValor().toString())<Integer.parseInt(n.toString());break;
                    case "==":PrincipalCompi.valueb=Integer.parseInt(a.getValor().toString())==Integer.parseInt(n.toString());break;
                    case "!=": PrincipalCompi.valueb=Integer.parseInt(a.getValor().toString())!=Integer.parseInt(n.toString());break;
                    case ">=": PrincipalCompi.valueb=Integer.parseInt(a.getValor().toString())>=Integer.parseInt(n.toString());break;
                    case "<=": PrincipalCompi.valueb=Integer.parseInt(a.getValor().toString())<=Integer.parseInt(n.toString());break;
                    case ">>": PrincipalCompi.valueb=Integer.parseInt(a.getValor().toString())>Integer.parseInt(n.toString());break;
                    case "<<": PrincipalCompi.valueb=Integer.parseInt(a.getValor().toString())<Integer.parseInt(n.toString());break;
                    default:break;
                }
            }
        }
    }
    :}|
    Numero:n Op_relacional:o Identificador:i {:
    PrincipalCompi.s_bool=PrincipalCompi.s_arit+"("+o+","+n+","+i+",TB"+PrincipalCompi.tempb+")\n";
    PrincipalCompi.temp++;
    Simbolo a=null;
    for(int it=0;it<PrincipalCompi.tabla_simbolos.size();it++){
        if(i.equals(PrincipalCompi.tabla_simbolos.get(it).getNombre().toString())){
            a=PrincipalCompi.tabla_simbolos.get(it);
        }
    }
    if(a==null){
        PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido declarado");
    }else{
        if(!a.getTipo().toString().equals("int")){
            PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no es de tipo int");
        }else{
            if(a.getValor()==null){
                PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido inicializado");
            }else{
                switch(o.toString()){
                    case ">":PrincipalCompi.valueb=Integer.parseInt(n.toString())>Integer.parseInt(a.getValor().toString());break;
                    case "<":PrincipalCompi.valueb=Integer.parseInt(n.toString())<Integer.parseInt(a.getValor().toString());break;
                    case "==":PrincipalCompi.valueb=Integer.parseInt(n.toString())==Integer.parseInt(a.getValor().toString());break;
                    case "!=": PrincipalCompi.valueb=Integer.parseInt(n.toString())!=Integer.parseInt(a.getValor().toString());break;
                    case ">=": PrincipalCompi.valueb=Integer.parseInt(n.toString())>=Integer.parseInt(a.getValor().toString());break;
                    case "<=": PrincipalCompi.valueb=Integer.parseInt(n.toString())<=Integer.parseInt(a.getValor().toString());break;
                    case ">>": PrincipalCompi.valueb=Integer.parseInt(n.toString())>Integer.parseInt(a.getValor().toString());break;
                    case "<<": PrincipalCompi.valueb=Integer.parseInt(n.toString())<Integer.parseInt(a.getValor().toString());break;
                    default:break;
                }
            }
        }
    }
    :}|
;
SENTENCIA_ARITMETICA ::=
    Numero:n Suma:s Numero:i {:
    PrincipalCompi.s_arit="("+s+","+n+","+i+",TA"+PrincipalCompi.temp+")\n";
    PrincipalCompi.value=Integer.parseInt(n.toString())+Integer.parseInt(i.toString());
    PrincipalCompi.expresiones.add(n+""+s+""+i);
    :} |
    Identificador:i Suma:s Numero:n {:
    PrincipalCompi.s_arit="("+s+","+i+","+n+",TA"+PrincipalCompi.temp+")\n";
    PrincipalCompi.expresiones.add(i+""+s+""+n);
        Simbolo a=null;
        for(int it=0;it<PrincipalCompi.tabla_simbolos.size();it++){
            if(i.equals(PrincipalCompi.tabla_simbolos.get(it).getNombre().toString())){
                a=PrincipalCompi.tabla_simbolos.get(it);
            }
        }
        if(a==null){
            PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido declarado");
        }else{
            if(!a.getTipo().equals("int")){
                PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no es de tipo int");
            }else{
                if(a.getValor()==null){
                    PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido inicializado");
                }else{
                    PrincipalCompi.value=Integer.parseInt(a.getValor().toString())+Integer.parseInt(n.toString());
                }
            }
        }
    :} |
    Numero:n Suma:s Identificador:i {:
    PrincipalCompi.s_arit="("+s+","+n+","+i+",TA"+PrincipalCompi.temp+")\n";
    PrincipalCompi.expresiones.add(n+""+s+""+i);
    Simbolo a=null;
        for(int it=0;it<PrincipalCompi.tabla_simbolos.size();it++){
            if(i.equals(PrincipalCompi.tabla_simbolos.get(it).getNombre().toString())){
                a=PrincipalCompi.tabla_simbolos.get(it);
            }
        }
        if(a==null){
            PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido declarado");
        }else{
            if(!a.getTipo().toString().equals("int")){
                PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no es de tipo int");
            }else{
                if(a.getValor()==null){
                    PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido inicializado");
                }else{
                    PrincipalCompi.value=Integer.parseInt(n.toString())+Integer.parseInt(a.getValor().toString());
                }
            }
        }
        
    :} |
    Identificador:i Suma:s Identificador:n {:
    PrincipalCompi.s_arit="("+s+","+i+","+n+",TA"+PrincipalCompi.temp+")\n";
    PrincipalCompi.expresiones.add(i+""+s+""+n);
    Simbolo a=null;
    Simbolo b=null;
        for(int it=0;it<PrincipalCompi.tabla_simbolos.size();it++){
            if(i.equals(PrincipalCompi.tabla_simbolos.get(it).getNombre().toString())){
                a=PrincipalCompi.tabla_simbolos.get(it);
            }
            if(n.equals(PrincipalCompi.tabla_simbolos.get(it).getNombre().toString())){
                b=PrincipalCompi.tabla_simbolos.get(it);
            }
        }
        if(a==null || b==null){
            if(a==null){
                PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido declarado");
            }
            if(b==null){
                PrincipalCompi.err.add("Error semántico linea:"+(nright+1)+"; el identificador "+n+" no ha sido declarado");
            }
        }else{
            if(!a.getTipo().toString().equals("int") || !b.getTipo().toString().equals("int")){
                if(!a.getTipo().toString().equals("int")){
                    PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no es de tipo int");
                }
                if(!b.getTipo().toString().equals("int")){
                    PrincipalCompi.err.add("Error semántico linea:"+(nright+1)+"; el identificador "+n+" no es de tipo int");
                }
            }else{
                if(a.getValor()==null||b.getValor()==null){
                    if(a.getValor()==null){
                        PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido inicializado");
                    }
                    if(b.getValor()==null){
                        PrincipalCompi.err.add("Error semántico linea:"+(nright+1)+"; el identificador "+n+" no ha sido inicializado");
                    }
                }else{
                    PrincipalCompi.value=Integer.parseInt(a.getValor().toString())+Integer.parseInt(b.getValor().toString());
                }
            }
        }
        

    :} |
    Numero:n Resta:s Numero:i {:
    PrincipalCompi.s_arit="("+s+","+n+","+i+",TA"+PrincipalCompi.temp+")\n";
    PrincipalCompi.value=Integer.parseInt(n.toString())-Integer.parseInt(i.toString());
    PrincipalCompi.expresiones.add(n+""+s+""+i);
    :} |
    Identificador:i Resta:s Numero:n {:
    PrincipalCompi.s_arit="("+s+","+i+","+n+",TA"+PrincipalCompi.temp+")\n";
    PrincipalCompi.expresiones.add(i+""+s+""+n);
    Simbolo a=null;
        for(int it=0;it<PrincipalCompi.tabla_simbolos.size();it++){
            if(i.equals(PrincipalCompi.tabla_simbolos.get(it).getNombre().toString())){
                a=PrincipalCompi.tabla_simbolos.get(it);
            }
        }
        if(a==null){
            PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido declarado");
        }else{
            if(!a.getTipo().toString().equals("int")){
                PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no es de tipo int");
            }else{
                if(a.getValor()==null){
                    PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido inicializado");
                }else{
                    PrincipalCompi.value=Integer.parseInt(a.getValor().toString())-Integer.parseInt(n.toString());
                }
            }
        }
    :} |
    Numero:n Resta:s Identificador:i {:
    PrincipalCompi.s_arit="("+s+","+n+","+i+",TA"+PrincipalCompi.temp+")\n";
    PrincipalCompi.expresiones.add(n+""+s+""+i);
    Simbolo a=null;
        for(int it=0;it<PrincipalCompi.tabla_simbolos.size();it++){
            if(i.equals(PrincipalCompi.tabla_simbolos.get(it).getNombre().toString())){
                a=PrincipalCompi.tabla_simbolos.get(it);
            }
        }
        if(a==null){
            PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido declarado");
        }else{
            if(!a.getTipo().toString().equals("int")){
                PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no es de tipo int");
            }else{
                if(a.getValor()==null){
                    PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido inicializado");
                }else{
                    PrincipalCompi.value=Integer.parseInt(n.toString())-Integer.parseInt(a.getValor().toString());
                }
            }
        }
        
    :} |
    Identificador:i Resta:s Identificador:n {:
    PrincipalCompi.s_arit="("+s+","+i+","+n+",TA"+PrincipalCompi.temp+")\n";
    PrincipalCompi.expresiones.add(i+""+s+""+n);
    Simbolo a=null;
    Simbolo b=null;
        for(int it=0;it<PrincipalCompi.tabla_simbolos.size();it++){
            if(i.equals(PrincipalCompi.tabla_simbolos.get(it).getNombre().toString())){
                a=PrincipalCompi.tabla_simbolos.get(it);
            }
            if(n.equals(PrincipalCompi.tabla_simbolos.get(it).getNombre().toString())){
                b=PrincipalCompi.tabla_simbolos.get(it);
            }
        }
        if(a==null || b==null){
            if(a==null){
                PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido declarado");
            }
            if(b==null){
                PrincipalCompi.err.add("Error semántico linea:"+(nright+1)+"; el identificador "+n+" no ha sido declarado");
            }
        }else{
            if(!a.getTipo().toString().equals("int") || !b.getTipo().toString().equals("int")){
                if(!a.getTipo().toString().equals("int")){
                    PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no es de tipo int");
                }
                if(!b.getTipo().toString().equals("int")){
                    PrincipalCompi.err.add("Error semántico linea:"+(nright+1)+"; el identificador "+n+" no es de tipo int");
                }
            }else{
                if(a.getValor()==null||b.getValor()==null){
                    if(a.getValor()==null){
                        PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido inicializado");
                    }
                    if(b.getValor()==null){
                        PrincipalCompi.err.add("Error semántico linea:"+(nright+1)+"; el identificador "+n+" no ha sido inicializado");
                    }
                }else{
                    PrincipalCompi.value=Integer.parseInt(a.getValor().toString())+Integer.parseInt(b.getValor().toString());
                }
            }
        }
        
    :} |
    Numero:n Multiplicacion:s Numero:i {:
    PrincipalCompi.s_arit="("+s+","+n+","+i+",TA"+PrincipalCompi.temp+")\n";
    PrincipalCompi.value=Integer.parseInt(n.toString())*Integer.parseInt(i.toString());
    PrincipalCompi.expresiones.add(n+""+s+""+i);
    :} |
    Identificador:i Multiplicacion:s Numero:n {:
    PrincipalCompi.s_arit="("+s+","+i+","+n+",TA"+PrincipalCompi.temp+")\n";
    PrincipalCompi.expresiones.add(i+""+s+""+n);
    Simbolo a=null;
        for(int it=0;it<PrincipalCompi.tabla_simbolos.size();it++){
            if(i.equals(PrincipalCompi.tabla_simbolos.get(it).getNombre().toString())){
                a=PrincipalCompi.tabla_simbolos.get(it);
            }
        }
        if(a==null){
            PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido declarado");
        }else{
            if(!a.getTipo().toString().equals("int")){
                PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no es de tipo int");
            }else{
                if(a.getValor()==null){
                    PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido inicializado");
                }else{
                    PrincipalCompi.value=Integer.parseInt(a.getValor().toString())*Integer.parseInt(n.toString());
                }
            }
        }
    :} |
    Numero:n Multiplicacion:s Identificador:i {:
    PrincipalCompi.s_arit="("+s+","+n+","+i+",TA"+PrincipalCompi.temp+")\n";
    PrincipalCompi.expresiones.add(n+""+s+""+i);
    Simbolo a=null;
        for(int it=0;it<PrincipalCompi.tabla_simbolos.size();it++){
            if(i.equals(PrincipalCompi.tabla_simbolos.get(it).getNombre().toString())){
                a=PrincipalCompi.tabla_simbolos.get(it);
            }
        }
        if(a==null){
            PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido declarado");
        }else{
            if(!a.getTipo().toString().equals("int")){
                PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no es de tipo int");
            }else{
                if(a.getValor()==null){
                    PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido inicializado");
                }else{
                    PrincipalCompi.value=Integer.parseInt(n.toString())*Integer.parseInt(a.getValor().toString());
                }
            }
        }
        
    :} |
    Identificador:i Multiplicacion:s Identificador:n {:
    PrincipalCompi.s_arit="("+s+","+i+","+n+",TA"+PrincipalCompi.temp+")\n";
    PrincipalCompi.expresiones.add(i+""+s+""+n);
    Simbolo a=null;
    Simbolo b=null;
        for(int it=0;it<PrincipalCompi.tabla_simbolos.size();it++){
            if(i.equals(PrincipalCompi.tabla_simbolos.get(it).getNombre().toString())){
                a=PrincipalCompi.tabla_simbolos.get(it);
            }
            if(n.equals(PrincipalCompi.tabla_simbolos.get(it).getNombre().toString())){
                b=PrincipalCompi.tabla_simbolos.get(it);
            }
        }
        if(a==null || b==null){
            if(a==null){
                PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido declarado");
            }
            if(b==null){
                PrincipalCompi.err.add("Error semántico linea:"+(nright+1)+"; el identificador "+n+" no ha sido declarado");
            }
        }else{
            if(!a.getTipo().toString().equals("int") || !b.getTipo().toString().equals("int")){
                if(!a.getTipo().toString().equals("int")){
                    PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no es de tipo int");
                }
                if(!b.getTipo().toString().equals("int")){
                    PrincipalCompi.err.add("Error semántico linea:"+(nright+1)+"; el identificador "+n+" no es de tipo int");
                }
            }else{
                if(a.getValor()==null||b.getValor()==null){
                    if(a.getValor()==null){
                        PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido inicializado");
                    }
                    if(b.getValor()==null){
                        PrincipalCompi.err.add("Error semántico linea:"+(nright+1)+"; el identificador "+n+" no ha sido inicializado");
                    }
                }else{
                    PrincipalCompi.value=Integer.parseInt(a.getValor().toString())+Integer.parseInt(b.getValor().toString());
                }
            }
        }
        
    :} |
    Numero:n Division:s Numero:i {:
    PrincipalCompi.s_arit="("+s+","+n+","+i+",TA"+PrincipalCompi.temp+")\n";
    PrincipalCompi.value=Integer.parseInt(n.toString())/Integer.parseInt(i.toString());
    PrincipalCompi.expresiones.add(n+""+s+""+i);
    :} |
    Identificador:i Division:s Numero:n {:
    PrincipalCompi.s_arit="("+s+","+i+","+n+",TA"+PrincipalCompi.temp+")\n";
    PrincipalCompi.expresiones.add(i+""+s+""+n);
    Simbolo a=null;
        for(int it=0;it<PrincipalCompi.tabla_simbolos.size();it++){
            if(i.equals(PrincipalCompi.tabla_simbolos.get(it).getNombre())){
                a=PrincipalCompi.tabla_simbolos.get(it);
            }
        }
        if(a==null){
            PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido declarado");
        }else{
            if(!a.getTipo().toString().equals("int")){
                PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no es de tipo int");
            }else{
                if(a.getValor()==null){
                    PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido inicializado");
                }else{
                    PrincipalCompi.value=Integer.parseInt(a.getValor().toString())/Integer.parseInt(n.toString());
                }
            }
        }
    :} |
    Numero:n Division:s Identificador:i {:
    PrincipalCompi.s_arit="("+s+","+n+","+i+",TA"+PrincipalCompi.temp+")\n";
    PrincipalCompi.expresiones.add(n+""+s+""+i);
    Simbolo a=null;
        for(int it=0;it<PrincipalCompi.tabla_simbolos.size();it++){
            if(i.equals(PrincipalCompi.tabla_simbolos.get(it).getNombre().toString())){
                a=PrincipalCompi.tabla_simbolos.get(it);
            }
        }
        if(a==null){
            PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido declarado");
        }else{
            if(!a.getTipo().toString().equals("int")){
                PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no es de tipo int");
            }else{
                if(a.getValor()==null){
                    PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido inicializado");
                }else{
                    PrincipalCompi.value=Integer.parseInt(n.toString())/Integer.parseInt(a.getValor().toString());
                }
            }
        }
        
    :} |
    Identificador:i Division:s Identificador:n {:
    PrincipalCompi.s_arit="("+s+","+i+","+n+",TA"+PrincipalCompi.temp+")\n";
    PrincipalCompi.expresiones.add(i+""+s+""+n);
    Simbolo a=null;
    Simbolo b=null;
        for(int it=0;it<PrincipalCompi.tabla_simbolos.size();it++){
            if(i.equals(PrincipalCompi.tabla_simbolos.get(it).getNombre().toString())){
                a=PrincipalCompi.tabla_simbolos.get(it);
            }
            if(n.equals(PrincipalCompi.tabla_simbolos.get(it).getNombre().toString())){
                b=PrincipalCompi.tabla_simbolos.get(it);
            }
        }
        if(a==null || b==null){
            if(a==null){
                PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido declarado");
            }
            if(b==null){
                PrincipalCompi.err.add("Error semántico linea:"+(nright+1)+"; el identificador "+n+" no ha sido declarado");
            }
        }else{
            if(!a.getTipo().toString().equals("int") || !b.getTipo().toString().equals("int")){
                if(!a.getTipo().toString().equals("int")){
                    PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no es de tipo int");
                }
                if(!b.getTipo().toString().equals("int")){
                    PrincipalCompi.err.add("Error semántico linea:"+(nright+1)+"; el identificador "+n+" no es de tipo int");
                }
            }else{
                if(a.getValor()==null||b.getValor()==null){
                    if(a.getValor()==null){
                        PrincipalCompi.err.add("Error semántico linea:"+(iright+1)+"; el identificador "+i+" no ha sido inicializado");
                    }
                    if(b.getValor()==null){
                        PrincipalCompi.err.add("Error semántico linea:"+(nright+1)+"; el identificador "+n+" no ha sido inicializado");
                    }
                }else{
                    PrincipalCompi.value=Integer.parseInt(a.getValor().toString())+Integer.parseInt(b.getValor().toString());
                }
            }
        }
        
    :}
;
WHILE ::= While Parentesis_a SENTENCIA_BOOLEANA Parentesis_c Llave_a SENTENCIA Llave_c {:
    PrincipalCompi.status--;
    PrincipalCompi.whiles="startloop"+PrincipalCompi.loop+":\n"+PrincipalCompi.s_bool+"(jf loop"+PrincipalCompi.loop+":,TB"+PrincipalCompi.tempb+", , )\n";
    PrincipalCompi.whiles=PrincipalCompi.whiles+PrincipalCompi.sentencia[PrincipalCompi.status]+"(jmp startloop"+PrincipalCompi.loop+":, , , )\nloop"+PrincipalCompi.loop+":\n";
    PrincipalCompi.loop++;
    PrincipalCompi.tempb++;
    PrincipalCompi.s_bool=PrincipalCompi.sentencia[PrincipalCompi.status]="";
    :} |
    While Parentesis_a Op_booleano:o Parentesis_c Llave_a SENTENCIA Llave_c {:
    PrincipalCompi.status--;
    PrincipalCompi.whiles="startloop"+PrincipalCompi.loop+":\n"+"(jf loop"+PrincipalCompi.loop+":,"+o+", , )\n";
    PrincipalCompi.whiles=PrincipalCompi.whiles+PrincipalCompi.sentencia[PrincipalCompi.status]+"(jmp startloop"+PrincipalCompi.loop+":, , , )\nloop"+PrincipalCompi.loop+":\n";
    PrincipalCompi.loop++;
    PrincipalCompi.s_bool=PrincipalCompi.sentencia[PrincipalCompi.status]="";
    :} |
    While Parentesis_a Identificador:o Parentesis_c Llave_a SENTENCIA Llave_c {:
    PrincipalCompi.status--;
    PrincipalCompi.whiles="startloop"+PrincipalCompi.loop+":\n"+"(jf loop"+PrincipalCompi.loop+":,"+o+", , )\n";
    PrincipalCompi.whiles=PrincipalCompi.whiles+PrincipalCompi.sentencia[PrincipalCompi.status]+"(jmp startloop"+PrincipalCompi.loop+":, , , )\nloop"+PrincipalCompi.loop+":\n";
    PrincipalCompi.loop++;
    PrincipalCompi.s_bool=PrincipalCompi.sentencia[PrincipalCompi.status]="";
    Simbolo a=null;
        for(int it=0;it<PrincipalCompi.tabla_simbolos.size();it++){
            if(o.equals(PrincipalCompi.tabla_simbolos.get(it).getNombre().toString())){
                a=PrincipalCompi.tabla_simbolos.get(it);
            }
        }
        if(a==null){
            PrincipalCompi.err.add("Error semántico linea:"+(oright+1)+"; el identificador "+o+" no ha sido declarado");
        }else{
            if(!a.getTipo().toString().equals("bool")){
                PrincipalCompi.err.add("Error semántico linea:"+(oright+1)+"; el identificador "+o+" no es de tipo bool");
            }else{
                if(a.getValor()==null){
                    PrincipalCompi.err.add("Error semántico linea:"+(oright+1)+"; el identificador "+o+" no ha sido inicializado");
                }
            }
        }
    :}
;
DO_WHILE ::= Do Llave_a SENTENCIA Llave_c While Parentesis_a SENTENCIA_BOOLEANA Parentesis_c P_coma {:
    PrincipalCompi.status--;
    PrincipalCompi.dowhiles="startloop"+PrincipalCompi.loop+":\n"+PrincipalCompi.sentencia[PrincipalCompi.status]+PrincipalCompi.s_bool;
    PrincipalCompi.dowhiles=PrincipalCompi.dowhiles+"(jt startloop"+PrincipalCompi.loop+":,TB"+PrincipalCompi.tempb+", , )\nloop"+PrincipalCompi.loop+":\n";
    PrincipalCompi.tempb++;
    PrincipalCompi.loop++;
    PrincipalCompi.sentencia[PrincipalCompi.status]=PrincipalCompi.s_bool="";
    :} |
    Do Llave_a SENTENCIA Llave_c While Parentesis_a Op_booleano:o Parentesis_c P_coma {:
    PrincipalCompi.status--;
    PrincipalCompi.dowhiles="startloop"+PrincipalCompi.loop+":\n"+PrincipalCompi.sentencia[PrincipalCompi.status];
    PrincipalCompi.dowhiles=PrincipalCompi.dowhiles+"(jt startloop"+PrincipalCompi.loop+":,"+o+", , )\nloop"+PrincipalCompi.loop+":\n";
    PrincipalCompi.loop++;
    PrincipalCompi.sentencia[PrincipalCompi.status]="";
    :} |
    Do Llave_a SENTENCIA Llave_c While Parentesis_a Identificador:o Parentesis_c P_coma {:
    PrincipalCompi.status--;
    PrincipalCompi.dowhiles="startloop"+PrincipalCompi.loop+":\n"+PrincipalCompi.sentencia[PrincipalCompi.status];
    PrincipalCompi.dowhiles=PrincipalCompi.dowhiles+"(jt startloop"+PrincipalCompi.loop+":,"+o+", , )\nloop"+PrincipalCompi.loop+":\n";
    PrincipalCompi.loop++;
    PrincipalCompi.sentencia[PrincipalCompi.status]="";
    Simbolo a=null;
        for(int it=0;it<PrincipalCompi.tabla_simbolos.size();it++){
            if(o.equals(PrincipalCompi.tabla_simbolos.get(it).getNombre().toString())){
                a=PrincipalCompi.tabla_simbolos.get(it);
            }
        }
        if(a==null){
            PrincipalCompi.err.add("Error semántico linea:"+(oright+1)+"; el identificador "+o+" no ha sido declarado");
        }else{
            if(!a.getTipo().toString().equals("bool")){
                PrincipalCompi.err.add("Error semántico linea:"+(oright+1)+"; el identificador "+o+" no es de tipo bool");
            }else{
                if(a.getValor()==null){
                    PrincipalCompi.err.add("Error semántico linea:"+(oright+1)+"; el identificador "+o+" no ha sido inicializado");
                }
            }
        }
    :}
    
;