
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Nov 25 21:10:40 MST 2019
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 27;
  public static final int SpinCraneLeft = 13;
  public static final int Llave_c = 34;
  public static final int Op_booleano = 30;
  public static final int Llave_a = 33;
  public static final int If = 7;
  public static final int WaitTime = 41;
  public static final int Else = 8;
  public static final int Start = 37;
  public static final int MoveFowardCrane = 15;
  public static final int Corchete_c = 36;
  public static final int Corchete_a = 35;
  public static final int StopLoop = 12;
  public static final int While = 10;
  public static final int Division = 25;
  public static final int Int = 4;
  public static final int HitToTheLeft = 19;
  public static final int Cadena = 6;
  public static final int Parentesis_c = 32;
  public static final int Parentesis_a = 31;
  public static final int For = 11;
  public static final int P_coma = 38;
  public static final int EOF = 0;
  public static final int SpinBallRight = 18;
  public static final int error = 1;
  public static final int Linea = 2;
  public static final int Op_atribucion = 28;
  public static final int ERROR = 42;
  public static final int Do = 9;
  public static final int Op_logico = 26;
  public static final int SpinCraneRight = 14;
  public static final int MoveBackCrane = 16;
  public static final int Identificador = 39;
  public static final int Resta = 23;
  public static final int Bool = 5;
  public static final int Multiplicacion = 24;
  public static final int SpinBallLeft = 17;
  public static final int Op_incremento = 29;
  public static final int Numero = 40;
  public static final int Suma = 22;
  public static final int HitToTheRight = 20;
  public static final int Igual = 21;
  public static final int Comillas = 3;
}

