
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Dec 05 11:49:21 MST 2019
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 25;
  public static final int SpinCraneLeft = 11;
  public static final int Llave_c = 32;
  public static final int Op_booleano = 28;
  public static final int Llave_a = 31;
  public static final int If = 5;
  public static final int WaitTime = 39;
  public static final int Else = 6;
  public static final int Start = 35;
  public static final int MoveFowardCrane = 13;
  public static final int Corchete_c = 34;
  public static final int Corchete_a = 33;
  public static final int StopLoop = 10;
  public static final int While = 8;
  public static final int Division = 23;
  public static final int Int = 3;
  public static final int HitToTheLeft = 17;
  public static final int Parentesis_c = 30;
  public static final int Parentesis_a = 29;
  public static final int For = 9;
  public static final int P_coma = 36;
  public static final int EOF = 0;
  public static final int SpinBallRight = 16;
  public static final int error = 1;
  public static final int Linea = 2;
  public static final int Op_atribucion = 26;
  public static final int ERROR = 40;
  public static final int Do = 7;
  public static final int Op_logico = 24;
  public static final int SpinCraneRight = 12;
  public static final int MoveBackCrane = 14;
  public static final int Identificador = 37;
  public static final int Resta = 21;
  public static final int Bool = 4;
  public static final int Multiplicacion = 22;
  public static final int SpinBallLeft = 15;
  public static final int Op_incremento = 27;
  public static final int Numero = 38;
  public static final int Suma = 20;
  public static final int HitToTheRight = 18;
  public static final int Igual = 19;
}

